import type { PdpAssessmentStatus,PdpEvidenceMatrixRow,PdpEvidenceReadinessState,PdpEvidenceSourceType,PdpRegulatoryReference } from "@/types/pdp";

export type MatrixControlInput={id:string;code:string;name:string;domain:string;assessment:PdpAssessmentStatus;references:PdpRegulatoryReference[];evidence:{reviewStatus:string}[]};
export type MatrixFacts={processingActivities:number;ropaRecorded:Partial<Record<string,number>>;confirmedBreaches:number;technical:Partial<Record<string,"available"|"unavailable">>;summaries:Partial<Record<string,string>>};
const ropaFields:Record<string,string>={"PDP-DG-01":"total","PDP-DG-02":"categories","PDP-DG-03":"owners","PDP-DG-04":"purposes","PDP-DG-05":"dataFlows","PDP-DG-06":"retention","PDP-DG-07":"locations","PDP-PC-02":"lawfulBasis","PDP-PC-05":"sharingStates"};
const technicalSources:Record<string,PdpEvidenceSourceType[]>={"PDP-SC-01":["Technical"],"PDP-SC-03":["Technical"],"PDP-SC-04":["Technical","Threat Intelligence"],"PDP-SC-06":["Technical","Incident Lifecycle","PDP Breach Register"],"PDP-PC-06":["Third-Party Register","RoPA","Evidence Registry"],"PDP-PB-01":["Technical","Incident Lifecycle","PDP Breach Register"]};
const breachControls=new Set(["PDP-PB-01","PDP-PB-02","PDP-PB-03","PDP-PB-04","PDP-PB-05","PDP-PB-06"]);
const missing:Record<string,string>={"PDP-DG-01":"Genuine processing-activity records","PDP-DG-02":"Personal-data category records","PDP-DG-03":"Accountable-owner records","PDP-DG-04":"Processing-purpose records","PDP-DG-05":"Documented data-flow references","PDP-DG-06":"Retention requirements","PDP-DG-07":"Processing-location records","PDP-SC-01":"IAM policy, access matrix, approvals, reviews, and revocation evidence","PDP-SC-02":"Encryption policy, scope, configurations, and key-management evidence","PDP-SC-03":"Logging scope, policy, retention, access governance, and review evidence","PDP-SC-04":"Monitoring scope, ownership, cadence, escalation, and review evidence","PDP-SC-05":"Backup policy, job history, restore tests, recovery objectives, and ownership","PDP-SC-06":"Incident-response plan, roles, escalation, classification, and exercise evidence","PDP-PC-01":"Approved policy, owner, approval, version, scope, publication, and review evidence","PDP-PC-02":"Lawful-basis decisions and consent evidence where applicable","PDP-PC-03":"DSR procedure, request workflow, ownership, SLA, and execution evidence","PDP-PC-04":"Retention schedule, deletion procedure, execution, and enforcement evidence","PDP-PC-05":"Sharing recipients, purpose, basis, agreements, and transfer evidence","PDP-PC-06":"Vendor PDP relationship, role, scope, DPA, location, transfer, and privacy review","PDP-PB-01":"Confirmed breach classification and complete verified chronology","PDP-PB-02":"Confirmed breach impact assessment evidence","PDP-PB-03":"Confirmed affected personal-data determination","PDP-PB-04":"Confirmed affected data-subject scope","PDP-PB-05":"Confirmed breach response status evidence and procedure","PDP-PB-06":"Notification procedure, decision, owner, recipients, dispatch, and timestamp evidence"};

export function derivePdpEvidenceMatrix(controls:MatrixControlInput[],facts:MatrixFacts):PdpEvidenceMatrixRow[]{return controls.map(control=>{const code=control.code,verified=control.evidence.some(e=>e.reviewStatus==="verified"),pending=control.evidence.some(e=>e.reviewStatus==="pending_review"),registered=control.evidence.length>0,technical=facts.technical[code],ropaField=ropaFields[code],ropaRecorded=ropaField?facts.ropaRecorded[ropaField]??0:0;let readiness:PdpEvidenceReadinessState;if(verified)readiness="verified_evidence_available";else if(pending)readiness="evidence_pending_review";else if(technical==="unavailable")readiness="unavailable";else if(technical==="available")readiness="candidate_evidence_available";else if(ropaField)readiness=facts.processingActivities===0?"awaiting_organizational_data":ropaRecorded===facts.processingActivities?"candidate_evidence_available":"incomplete_evidence";else if(breachControls.has(code)&&facts.confirmedBreaches>0)readiness="candidate_evidence_available";else if(registered)readiness="evidence_registered";else readiness="insufficient_evidence";const sources=[...(technicalSources[code]??[])] as PdpEvidenceSourceType[];if(ropaField&&!sources.includes("RoPA"))sources.push("RoPA");if(breachControls.has(code)&&!sources.includes("PDP Breach Register"))sources.push("PDP Breach Register");if(!sources.includes("Evidence Registry"))sources.push("Evidence Registry");const nextAction=readiness==="awaiting_organizational_data"?"Add Processing Activity":breachControls.has(code)&&facts.confirmedBreaches>0?"Review Breach Evidence":readiness==="candidate_evidence_available"?"Review Candidate Evidence":registered?"Start Assessment":"Register Evidence";return {controlId:control.id,controlCode:code,controlName:control.name,domain:control.domain,regulatoryBasis:control.references.map(r=>r.referenceIdentifier??"No direct article mapping"),relationshipTypes:control.references.map(r=>r.relationshipType),sourceTypes:sources,currentEvidence:facts.summaries[code]??(ropaField?(facts.processingActivities===0?"0 processing activities recorded":`${ropaRecorded} / ${facts.processingActivities} relevant RoPA fields recorded`):breachControls.has(code)?`${facts.confirmedBreaches} confirmed PDP breach records · ${control.evidence.length} organizational evidence records`:`${control.evidence.length} organizational evidence records`),missingEvidence:missing[code]??"Assessor-approved organizational evidence",readiness,assessment:control.assessment,nextAction};});}

export function summarizePdpEvidenceReadiness(rows:PdpEvidenceMatrixRow[]):Record<PdpEvidenceReadinessState,number>{const states:PdpEvidenceReadinessState[]=["candidate_evidence_available","verified_evidence_available","evidence_registered","evidence_pending_review","awaiting_organizational_data","incomplete_evidence","insufficient_evidence","unavailable"];return Object.fromEntries(states.map(state=>[state,rows.filter(row=>row.readiness===state).length])) as Record<PdpEvidenceReadinessState,number>;}
