import { NextRequest, NextResponse } from "next/server";
import { getSessionFromRequest } from "@/lib/get-session";
import { listVulnerabilityInstances, resolveRemediation, startRemediation, updateRemediation, validateRemediationInput } from "@/services/vulnerability-remediation-service";

export const dynamic = "force-dynamic";
export async function GET(){try{const data=await listVulnerabilityInstances(100);return NextResponse.json({status:"ok",data:{items:data.items,totalInstances:data.total,observedAt:data.observedAt,storageAvailable:true}},{headers:{"Cache-Control":"no-store"}});}catch{return NextResponse.json({error:"Vulnerability or remediation source unavailable."},{status:503});}}
async function authorized(request:NextRequest){const user=await getSessionFromRequest(request);return user&&["admin","ciso"].includes(user.role)?user:null;}
export async function POST(request:NextRequest){const user=await authorized(request);if(!user)return NextResponse.json({error:"Admin or CISO authentication required."},{status:401});let body:unknown;try{body=await request.json();}catch{return NextResponse.json({error:"Invalid JSON."},{status:400});}const input=validateRemediationInput(body);if(!input)return NextResponse.json({error:"Invalid genuine vulnerability remediation input."},{status:400});try{return NextResponse.json({status:"ok",data:await startRemediation(input,user)},{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to start remediation."},{status:400});}}
export async function PATCH(request:NextRequest){const user=await authorized(request);if(!user)return NextResponse.json({error:"Admin or CISO authentication required."},{status:401});let body:Record<string,unknown>;try{body=await request.json();}catch{return NextResponse.json({error:"Invalid JSON."},{status:400});}const id=typeof body.id==="string"?body.id:"",action=body.action; if(!/^[0-9a-f-]{36}$/i.test(id))return NextResponse.json({error:"Valid remediation id required."},{status:400});try{if(action==="resolve")return NextResponse.json({status:"ok",data:await resolveRemediation(id,user)});if(action!=="update")return NextResponse.json({error:"Action must be update or resolve."},{status:400});const input=validateRemediationInput({sourceIndex:"update",sourceDocumentId:"update",owner:body.owner??null,targetDate:body.targetDate??null,notes:body.notes??null});if(!input)return NextResponse.json({error:"Invalid remediation update."},{status:400});return NextResponse.json({status:"ok",data:await updateRemediation(id,input,user)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to update remediation."},{status:400});}}
