"use client";

import { useState, type ReactNode } from "react";
import { Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Panel } from "@/components/ui/Panel";
import type { MsspDemoTicket, MsspDemoTicketPriority, MsspDemoTicketStatus, MsspTicketsDemoData } from "@/types/mssp";

const STATUSES: MsspDemoTicketStatus[] = ["Open", "In Progress", "Waiting", "Resolved", "Closed"];
const PRIORITIES: MsspDemoTicketPriority[] = ["Critical", "High", "Medium", "Low", "Informational"];
const STATUS_COLORS = ["#3b82f6", "#f97316", "#eab308", "#22c55e", "#64748b"];
const PRIORITY_COLORS = ["#dc2626", "#f97316", "#eab308", "#22c55e", "#3b82f6"];
const PAGE_SIZE = 10;
const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
const hours = (minutes: number) => `${(minutes / 60).toFixed(1)}h`;
const dateTime = (value: string) => new Date(value).toLocaleString("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "UTC" });

export function MsspTickets({ demo }: { demo: MsspTicketsDemoData }) {
  const [page, setPage] = useState(1);
  const tickets = [...demo.tickets].sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt));
  const countStatus = (status: MsspDemoTicketStatus) => tickets.filter((ticket) => ticket.status === status).length;
  const slaMet = tickets.filter((ticket) => ticket.slaStatus === "Met").length, breached = tickets.length - slaMet, slaPercent = slaMet / tickets.length * 100;
  const kpis = [
    ["Total Tickets", tickets.length, [tickets.length - 7, tickets.length - 6, tickets.length - 4, tickets.length - 2, tickets.length]],
    ["Open Tickets", countStatus("Open"), [countStatus("Open") + 3, countStatus("Open") + 2, countStatus("Open") + 1, countStatus("Open") + 1, countStatus("Open")]],
    ["In Progress Tickets", countStatus("In Progress"), [countStatus("In Progress") - 2, countStatus("In Progress") - 1, countStatus("In Progress"), countStatus("In Progress") + 1, countStatus("In Progress")]],
    ["Resolved Tickets", countStatus("Resolved"), [countStatus("Resolved") - 4, countStatus("Resolved") - 3, countStatus("Resolved") - 2, countStatus("Resolved") - 1, countStatus("Resolved")]],
    ["SLA Met", `${slaPercent.toFixed(1)}%`, [slaPercent - 2.2, slaPercent - 1.6, slaPercent - 1, slaPercent - .4, slaPercent]],
    ["SLA Breached", breached, [breached + 3, breached + 2, breached + 1, breached + 1, breached]],
  ] as const;
  const priorityRows = PRIORITIES.map((name, index) => ({ name, value: tickets.filter((ticket) => ticket.priority === name).length, color: PRIORITY_COLORS[index] }));
  const statusRows = STATUSES.map((name, index) => ({ name, value: countStatus(name), color: STATUS_COLORS[index] }));
  const categories = [...new Set(tickets.map((ticket) => ticket.category))].map((category, index) => ({ category, count: tickets.filter((ticket) => ticket.category === category).length, trend: ((index * 7) % 9) - 3 })).sort((a, b) => b.count - a.count);
  const timeline = Array.from({ length: 7 }, (_, index) => { const end = Date.parse(demo.snapshotAt) - (6 - index) * 86_400_000; const active = tickets.filter((ticket) => Date.parse(ticket.createdAt) <= end); return { date: new Date(end).toLocaleDateString("en-GB", { day: "2-digit", month: "short", timeZone: "UTC" }), Open: active.filter((ticket) => ticket.status === "Open").length, "In Progress": active.filter((ticket) => ticket.status === "In Progress").length, Resolved: active.filter((ticket) => ticket.status === "Resolved").length, Closed: active.filter((ticket) => ticket.status === "Closed").length }; });
  const pages = Math.ceil(tickets.length / PAGE_SIZE), current = Math.min(page, pages), start = (current - 1) * PAGE_SIZE, visible = tickets.slice(start, start + PAGE_SIZE);
  return <div className="space-y-4">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-xl font-semibold text-slate-800 dark:text-white">Tickets</h1><DemoBadge /></div><p className="mt-1 text-sm text-slate-500">Demo ticket workflow · Service Desk integration pending</p></div><p className="text-[10px] text-slate-400">Read-only deterministic preview · No external Service Desk connection</p></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{kpis.map(([title, value, history]) => <Kpi key={title} title={title} value={value} history={[...history]} />)}</section>
    <section className="grid items-stretch gap-4 xl:grid-cols-12"><Box span="xl:col-span-5" title="Tickets Over Time"><Timeline rows={timeline} /></Box><Box span="xl:col-span-3" title="Tickets by Priority"><Donut rows={priorityRows} total={tickets.length} /></Box><Box span="xl:col-span-4" title="Top Ticket Categories"><CategoryTable rows={categories} total={tickets.length} /></Box></section>
    <section className="grid items-stretch gap-4 xl:grid-cols-12"><Box span="xl:col-span-6" title="Recent Tickets"><Recent tickets={visible} demo={demo} start={start} total={tickets.length} page={current} pages={pages} onPage={setPage} /></Box><Box span="xl:col-span-3" title="Tickets by Status"><Donut rows={statusRows} total={tickets.length} /></Box><Box span="xl:col-span-3" title="SLA Performance"><Sla met={slaMet} breached={breached} total={tickets.length} /></Box></section>
    <section className="grid items-stretch gap-4 xl:grid-cols-12"><Box span="xl:col-span-3" title="Tickets by Client"><Aggregate rows={clientAggregation(tickets, demo)} /></Box><Box span="xl:col-span-4" title="Tickets by Assignee"><Aggregate rows={teamAggregation(tickets)} /></Box><Box span="xl:col-span-5" title="Average Resolution Time"><Resolution tickets={tickets} /></Box></section>
  </div>;
}

function DemoBadge() { return <span className="shrink-0 rounded-full border border-amber-200 bg-amber-50 px-2 py-0.5 text-[8px] font-bold uppercase tracking-wide text-amber-700 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300">Demo Data</span>; }
function Box({ span, title, children }: { span: string; title: string; children: ReactNode }) { return <div className={`min-w-0 ${span}`}><Panel title={title} action={<DemoBadge />}>{children}</Panel></div>; }
function Kpi({ title, value, history }: { title: string; value: string | number; history: number[] }) { const delta = history.at(-1)! - history[0]; return <article className="min-h-28 rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between gap-2"><p className="truncate text-[11px] font-semibold text-slate-500">{title}</p><DemoBadge /></div><div className="mt-2 grid grid-cols-[1fr_4.5rem] items-end"><div><p className="text-xl font-bold text-slate-800 dark:text-white">{value}</p><p className={`text-[9px] ${delta >= 0 ? "text-emerald-600" : "text-rose-500"}`}>{delta >= 0 ? "↑" : "↓"} {Math.abs(delta).toFixed(1)} <span className="text-slate-400">demo trend</span></p></div><div className="h-10"><ResponsiveContainer><LineChart data={history.map((point, i) => ({ i, point }))}><Line dataKey="point" stroke="#f59e0b" dot={false} strokeWidth={1.8} /></LineChart></ResponsiveContainer></div></div></article>; }
function Timeline({ rows }: { rows: Array<Record<string, string | number>> }) { return <div className="h-52"><ResponsiveContainer><LineChart data={rows} margin={{ top: 8, right: 8, left: -28 }}><XAxis dataKey="date" tick={{ fontSize: 8 }} /><YAxis allowDecimals={false} tick={{ fontSize: 8 }} /><Tooltip />{["Open", "In Progress", "Resolved", "Closed"].map((key, index) => <Line key={key} dataKey={key} stroke={STATUS_COLORS[[0, 1, 3, 4][index]]} dot={false} strokeWidth={1.8} />)}</LineChart></ResponsiveContainer></div>; }
function Donut({ rows, total }: { rows: Array<{ name: string; value: number; color: string }>; total: number }) { return <div className="grid h-52 grid-cols-[8.5rem_1fr] items-center gap-2"><div className="relative h-36"><ResponsiveContainer><PieChart><Pie data={rows} dataKey="value" innerRadius={44} outerRadius={64} strokeWidth={0}>{rows.map((row) => <Cell key={row.name} fill={row.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-xl">{total}</strong><span className="text-[8px] text-slate-400">Total Tickets</span></div></div><div className="space-y-1.5">{rows.map((row) => <div key={row.name} className="grid grid-cols-[auto_1fr_auto_auto] items-center gap-1 text-[9px]"><i className="h-1.5 w-1.5 rounded-full" style={{ background: row.color }} /><span className="truncate text-slate-500">{row.name}</span><strong>{row.value}</strong><span className="w-8 text-right text-slate-400">{(row.value / total * 100).toFixed(0)}%</span></div>)}</div></div>; }
function CategoryTable({ rows, total }: { rows: Array<{ category: string; count: number; trend: number }>; total: number }) { return <Table heads={["Category", "Tickets", "% of Total", "Trend"]}>{rows.map((row) => <tr key={row.category}><Td>{row.category}</Td><Td>{row.count}</Td><Td>{(row.count / total * 100).toFixed(1)}%</Td><Td><span className={row.trend >= 0 ? "text-emerald-600" : "text-rose-500"}>{row.trend >= 0 ? "↑" : "↓"} {Math.abs(row.trend)}%</span></Td></tr>)}</Table>; }
function Recent({ tickets, demo, start, total, page, pages, onPage }: { tickets: MsspDemoTicket[]; demo: MsspTicketsDemoData; start: number; total: number; page: number; pages: number; onPage: (page: number) => void }) { return <><Table width="760px" heads={["Ticket ID", "Client", "Subject", "Priority", "Status", "Assigned To", "Created At"]}>{tickets.map((ticket) => <tr key={ticket.id}><Td>{ticket.id}</Td><Td>{demo.clients.find((client) => client.id === ticket.clientId)?.name}</Td><Td title={ticket.subject}>{ticket.subject}</Td><Td><Tag value={ticket.priority} /></Td><Td><Tag value={ticket.status} /></Td><Td>{ticket.assignedTeam}</Td><Td>{dateTime(ticket.createdAt)}</Td></tr>)}</Table><div className="flex items-center justify-between px-2 py-2 text-[9px] text-slate-400"><span>Showing {start + 1}-{Math.min(start + PAGE_SIZE, total)} of {total} tickets</span><div className="flex gap-1"><button disabled={page === 1} onClick={() => onPage(page - 1)} className="rounded border px-2 py-1 disabled:opacity-40">Previous</button><button disabled={page === pages} onClick={() => onPage(page + 1)} className="rounded border px-2 py-1 disabled:opacity-40">Next</button></div></div></>; }
function Sla({ met, breached, total }: { met: number; breached: number; total: number }) { const metPct = met / total * 100; return <div className="flex h-52 flex-col items-center justify-center"><div className="relative h-32 w-40 overflow-hidden"><div className="absolute left-2 top-4 h-32 w-32 rounded-full border-[16px] border-slate-100 dark:border-slate-800" /><div className="absolute inset-x-0 top-14 text-center"><strong className="text-2xl">{metPct.toFixed(1)}%</strong><p className="text-[8px] text-slate-400">SLA Met</p></div></div><div className="grid w-full grid-cols-2 gap-2 text-center text-[9px]"><div><strong className="text-emerald-600">{metPct.toFixed(1)}%</strong><p className="text-slate-400">Met ({met})</p></div><div><strong className="text-rose-500">{(breached / total * 100).toFixed(1)}%</strong><p className="text-slate-400">Breached ({breached})</p></div></div></div>; }
type AggregateRow = { name: string; open: number; progress: number; resolved: number; total: number };
function clientAggregation(tickets: MsspDemoTicket[], demo: MsspTicketsDemoData) { return demo.clients.map((client) => aggregate(client.name, tickets.filter((ticket) => ticket.clientId === client.id))).sort((a, b) => b.total - a.total).slice(0, 7); }
function teamAggregation(tickets: MsspDemoTicket[]) { return [...new Set(tickets.map((ticket) => ticket.assignedTeam))].map((team) => aggregate(team, tickets.filter((ticket) => ticket.assignedTeam === team))).sort((a, b) => b.total - a.total); }
function aggregate(name: string, tickets: MsspDemoTicket[]): AggregateRow { return { name, open: tickets.filter((ticket) => ticket.status === "Open").length, progress: tickets.filter((ticket) => ticket.status === "In Progress").length, resolved: tickets.filter((ticket) => ticket.status === "Resolved").length, total: tickets.length }; }
function Aggregate({ rows }: { rows: AggregateRow[] }) { return <Table heads={["Name", "Open", "In Progress", "Resolved", "Total"]}>{rows.map((row) => <tr key={row.name}><Td title={row.name}>{row.name}</Td><Td>{row.open}</Td><Td>{row.progress}</Td><Td>{row.resolved}</Td><Td><strong>{row.total}</strong></Td></tr>)}</Table>; }
function Resolution({ tickets }: { tickets: MsspDemoTicket[] }) { const resolved = tickets.filter((ticket) => ticket.resolvedAt); const duration = (items: MsspDemoTicket[]) => average(items.map((ticket) => (Date.parse(ticket.resolvedAt!) - Date.parse(ticket.createdAt)) / 60_000)); const cards = [["Overall", duration(resolved)], ["Critical / High", duration(resolved.filter((ticket) => ticket.priority === "Critical" || ticket.priority === "High"))], ["Medium Priority", duration(resolved.filter((ticket) => ticket.priority === "Medium"))], ["Low Priority", duration(resolved.filter((ticket) => ticket.priority === "Low" || ticket.priority === "Informational"))]] as const; return <div className="grid min-h-44 grid-cols-2 gap-3 p-2">{cards.map(([label, value], index) => <div key={label} className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800/60"><p className="text-[9px] text-slate-400">{label}</p><p className="mt-1 text-xl font-bold">{hours(value)}</p><p className="mt-1 text-[8px] text-emerald-600">↓ {(1.2 + index * .4).toFixed(1)}% demo trend</p></div>)}</div>; }
function Table({ heads, children, width = "100%" }: { heads: string[]; children: ReactNode; width?: string }) { return <div className="overflow-x-auto"><table className="w-full table-fixed text-left text-[9px]" style={{ minWidth: width }}><thead className="border-b bg-slate-50/80 text-slate-400 dark:bg-slate-950/40"><tr>{heads.map((head) => <th key={head} className="px-2 py-2 font-semibold">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{children}</tbody></table></div>; }
function Td({ children, title }: { children: ReactNode; title?: string }) { return <td title={title} className="truncate px-2 py-2 text-slate-600 dark:text-slate-300">{children}</td>; }
function Tag({ value }: { value: string }) { return <span className="whitespace-nowrap rounded-full bg-slate-100 px-1.5 py-0.5 text-[8px] font-semibold dark:bg-slate-800">{value}</span>; }
