"use client";

import { useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Panel } from "@/components/ui/Panel";
import { useApiResult } from "@/hooks/useApiResult";
import type { MsspAlertsData, MsspDemoIncident, MsspOverviewDemoData } from "@/types/mssp";
import type { Severity, SocTelemetry } from "@/types/soc";

const SEVERITIES: Array<{ key: Severity; label: string; threshold: string; color: string }> = [
  { key: "critical", label: "Critical", threshold: "≥ 14", color: "#ef4444" },
  { key: "high", label: "High", threshold: "11–13", color: "#f97316" },
  { key: "medium", label: "Medium", threshold: "7–10", color: "#eab308" },
  { key: "low", label: "Low", threshold: "< 7", color: "#22c55e" },
];

export function MsspAlertsAndIncidents() {
  const state = useApiResult<MsspAlertsData>("/api/mssp/alerts");
  return <div className="space-y-3">
    <header className="flex flex-wrap items-start justify-between gap-3">
      <div><h1 className="text-xl font-semibold text-slate-800 dark:text-white">Alerts &amp; Incidents</h1><p className="mt-1 text-sm text-slate-500">Read-only operational visibility across integrated security sources.</p></div>
      <div className="text-right"><span className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-[10px] font-semibold uppercase tracking-wide text-amber-700 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300">Mixed: Live Security Telemetry + Demo Workflow Data</span><p className="mt-1 text-[10px] text-slate-400">Tenant filter unavailable · Last 7 days</p></div>
    </header>
    {state.phase === "loading" ? <PageState message="Loading integrated security telemetry…" /> : state.phase === "error" ? <PageState message="MSSP alert and incident sources are unavailable." error /> : state.phase === "empty" ? <PageState message="No alert and incident data is available." /> : <AlertsContent data={state.data} />}
  </div>;
}

function AlertsContent({ data }: { data: MsspAlertsData }) {
  const telemetry = data.telemetry.status === "available" ? data.telemetry.data : null;
  const demo = data.demo.status === "available" ? data.demo.data : null;
  const demoAttention = demo?.incidentKpiHistory.at(-1)?.needingAttention;
  const alertDocumentHistory = telemetry?.trend.map((point) => point.critical + point.high + point.medium + point.low) ?? [];
  return <>
    <section className="grid gap-2.5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
      <KpiCard title="Alert Documents" value={telemetry?.totalEvents} provenance={telemetry ? "REAL" : "UNAVAILABLE"} source="Wazuh / OpenSearch · Last 7 days" history={alertDocumentHistory} icon="alerts" />
      <KpiCard title="Critical Alerts" value={telemetry?.severity.critical} provenance={telemetry ? "REAL" : "UNAVAILABLE"} source="Rule level ≥ 14 · Last 7 days" history={telemetry?.trend.map((point) => point.critical) ?? []} icon="critical" />
      <KpiCard title="High Alerts" value={telemetry?.severity.high} provenance={telemetry ? "REAL" : "UNAVAILABLE"} source="Rule level 11–13 · Last 7 days" history={telemetry?.trend.map((point) => point.high) ?? []} icon="high" />
      <KpiCard title="Open Incidents" value={demo?.openIncidents} provenance={demo ? "DEMO" : "UNAVAILABLE"} source="Shared demo incident workflow" history={demo?.incidentKpiHistory.map((point) => point.openIncidents) ?? []} icon="incidents" />
      <KpiCard title="MTTR" value={demo ? `${demo.mttrMinutes} min` : undefined} provenance={demo ? "DEMO" : "UNAVAILABLE"} source="Resolved demo lifecycle records" history={demo?.incidentKpiHistory.map((point) => point.mttrMinutes) ?? []} icon="time" />
      <KpiCard title="Alerts Needing Attention" value={demoAttention} provenance={demo ? "DEMO" : "UNAVAILABLE"} source="Open New, Investigating, or SLA-breached workflow" history={demo?.incidentKpiHistory.map((point) => point.needingAttention) ?? []} icon="attention" />
    </section>
    <section className="grid gap-3 xl:grid-cols-12"><div className="xl:col-span-3"><SeverityPanel telemetry={telemetry} /></div><div className="xl:col-span-5"><TrendPanel telemetry={telemetry} /></div><div className="xl:col-span-4"><SourcesPanel telemetry={telemetry} /></div></section>
    <section className="grid items-stretch gap-3 xl:grid-cols-12"><div className="xl:col-span-4"><RecentAlertsPanel telemetry={telemetry} /></div><div className="xl:col-span-3"><IncidentStatusPanel demo={demo} /></div><div className="xl:col-span-5"><TopIncidentClientsPanel demo={demo} /></div></section>
    <section className="grid gap-3 xl:grid-cols-12"><div className="min-w-0 xl:col-span-8"><OpenIncidentTable demo={demo} /></div><div className="xl:col-span-4"><MitrePanel telemetry={telemetry} /></div></section>
  </>;
}

type IconName = "alerts" | "critical" | "high" | "incidents" | "time" | "attention";
function KpiCard({ title, value, provenance, source, history, icon }: { title: string; value?: number | string; provenance: "REAL" | "DEMO" | "UNAVAILABLE"; source: string; history: number[]; icon: IconName }) {
  const chartData = history.map((point, index) => ({ index, value: point }));
  return <article className="min-h-28 overflow-hidden rounded-xl border border-slate-200 bg-white p-3 shadow-sm shadow-slate-200/30 dark:border-slate-800 dark:bg-slate-900 dark:shadow-none"><div className="flex items-start justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><MetricIcon name={icon} /><p className="truncate text-[11px] font-semibold text-slate-500">{title}</p></div><SourceBadge provenance={provenance} /></div><div className="mt-1.5 grid grid-cols-[1fr_4.5rem] items-end gap-1"><div><p className="text-xl font-bold leading-none text-slate-800 dark:text-white">{value === undefined ? "N/A" : typeof value === "number" ? value.toLocaleString() : value}</p><p className="mt-1 line-clamp-2 text-[8px] leading-3 text-slate-400">{provenance === "UNAVAILABLE" ? "Source unavailable" : source}</p></div><div className="h-10">{history.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><Line type="monotone" dataKey="value" stroke={provenance === "REAL" ? "#2563eb" : "#f59e0b"} strokeWidth={1.8} dot={false} /></LineChart></ResponsiveContainer> : null}</div></div></article>;
}

function SeverityPanel({ telemetry }: { telemetry: SocTelemetry | null }) {
  const items = telemetry ? SEVERITIES.map((item) => ({ ...item, value: telemetry.severity[item.key], percentage: telemetry.severity.percentages[item.key] })) : [];
  return <Panel title="Alerts by Severity" action={<SourceBadge available={Boolean(telemetry)} />}>{!telemetry ? <Unavailable reason="Wazuh telemetry unavailable" /> : <div className="flex min-h-48 flex-col justify-center"><div className="relative h-32"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={items} dataKey="value" innerRadius={42} outerRadius={60} strokeWidth={0}>{items.map((item) => <Cell key={item.key} fill={item.color} />)}</Pie><Tooltip formatter={(value) => Number(value).toLocaleString()} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-lg font-bold text-slate-800 dark:text-white">{telemetry.severity.total.toLocaleString()}</span><span className="text-[8px] text-slate-400">classified</span></div></div><div className="space-y-1">{items.map((item) => <div key={item.key} className="grid grid-cols-[1fr_auto_auto] items-center gap-2 text-[9px]"><span className="flex items-center gap-1.5 text-slate-500"><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: item.color }} />{item.label} {item.threshold}</span><strong className="text-slate-700 dark:text-slate-200">{item.value.toLocaleString()}</strong><span className="w-9 text-right text-slate-400">{item.percentage.toFixed(1)}%</span></div>)}</div><SourceNote text="Wazuh / OpenSearch · All integrated telemetry" /></div>}</Panel>;
}

function TrendPanel({ telemetry }: { telemetry: SocTelemetry | null }) {
  const data = telemetry?.trend.map((point) => ({ ...point, day: formatDay(point.timestamp) })) ?? [];
  return <Panel title="Alerts Over Time" action={<SourceBadge available={Boolean(telemetry)} />}>{!telemetry ? <Unavailable reason="Wazuh telemetry unavailable" /> : data.length === 0 ? <Empty message="No trend buckets are available for this period." /> : <div className="flex min-h-48 flex-col justify-center"><div className="h-44"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 5, right: 8, left: -18 }}><defs>{SEVERITIES.map((item) => <linearGradient key={item.key} id={`mssp-${item.key}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={item.color} stopOpacity={0.22} /><stop offset="100%" stopColor={item.color} stopOpacity={0.01} /></linearGradient>)}</defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="day" tick={{ fontSize: 8 }} /><YAxis allowDecimals={false} tick={{ fontSize: 8 }} /><Tooltip formatter={(value, name) => [Number(value).toLocaleString(), String(name)]} />{SEVERITIES.map((item) => <Area key={item.key} type="monotone" dataKey={item.key} name={item.label} stroke={item.color} fill={`url(#mssp-${item.key})`} strokeWidth={1.6} />)}</AreaChart></ResponsiveContainer></div><div className="flex flex-wrap justify-center gap-3">{SEVERITIES.map((item) => <span key={item.key} className="flex items-center gap-1 text-[8px] text-slate-500"><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: item.color }} />{item.label}</span>)}</div><SourceNote text="Wazuh / OpenSearch · Last 7 days · UTC" /></div>}</Panel>;
}

function SourcesPanel({ telemetry }: { telemetry: SocTelemetry | null }) {
  const rows = telemetry ? [...telemetry.detectionSources.sources, ...(telemetry.detectionSources.unclassified > 0 ? [{ source: "Unclassified", count: telemetry.detectionSources.unclassified }] : [])].sort((a, b) => b.count - a.count) : [];
  const max = Math.max(1, ...rows.map((row) => row.count));
  return <Panel title="Top Alert Sources" action={<SourceBadge available={Boolean(telemetry)} />}>{!telemetry ? <Unavailable reason="Wazuh telemetry unavailable" /> : rows.length === 0 ? <Empty message="No detection-source documents in this period." /> : <div className="flex min-h-48 flex-col justify-center gap-2.5">{rows.slice(0, 6).map((row) => <div key={row.source} className="grid grid-cols-[7rem_1fr_4rem] items-center gap-2 text-[9px]"><span className="truncate font-medium text-slate-600 dark:text-slate-300" title={row.source}>{row.source}</span><div className="h-2 overflow-hidden rounded-full bg-red-50 dark:bg-red-950"><div className="h-full rounded-full bg-red-400" style={{ width: `${row.count / max * 100}%` }} /></div><span className="text-right text-slate-400">{row.count.toLocaleString()}</span></div>)}<SourceNote text="Application-classified Wazuh detection sources" /></div>}</Panel>;
}

function RecentAlertsPanel({ telemetry }: { telemetry: SocTelemetry | null }) {
  return <Panel title="Recent Alerts" action={<SourceBadge available={Boolean(telemetry)} />}>{!telemetry ? <Unavailable reason="Wazuh telemetry unavailable" /> : telemetry.liveEvents.length === 0 ? <Empty message="No Wazuh alert documents in this period." /> : <div className="min-w-0"><table className="w-full table-fixed text-left text-[9px]"><colgroup><col className="w-[18%]" /><col className="w-[32%]" /><col className="w-[12%]" /><col className="w-[20%]" /><col className="w-[18%]" /></colgroup><thead className="border-b border-slate-200 text-slate-400 dark:border-slate-800"><tr><TableHead>Time</TableHead><TableHead>Alert / Rule Description</TableHead><TableHead>Severity</TableHead><TableHead>Detection Source</TableHead><TableHead>Agent</TableHead></tr></thead><tbody>{telemetry.liveEvents.slice(0, 5).map((alert) => <tr key={alert.id} className="border-b border-slate-100 dark:border-slate-800"><TableCell muted><span className="block truncate" title={formatUtc(alert.time)}>{formatUtc(alert.time)}</span></TableCell><TableCell><span className="block truncate font-medium" title={alert.event}>{alert.event}</span><span className="block truncate text-[8px] text-slate-400">Rule {alert.rule}</span></TableCell><TableCell><SeverityLabel severity={alert.severity} /></TableCell><TableCell muted><span className="block truncate" title={alert.detectionSource ?? "Unclassified"}>{alert.detectionSource ?? "Unclassified"}</span></TableCell><TableCell muted><span className="block truncate" title={alert.source || "—"}>{alert.source || "—"}</span></TableCell></tr>)}</tbody></table><SourceNote text="Latest 5 · Wazuh / OpenSearch · Read-only" /></div>}</Panel>;
}

const INCIDENT_STATUS_COLORS: Record<MsspDemoIncident["status"], string> = { New: "#2563eb", Investigating: "#14b8a6", "In Progress": "#f59e0b", Contained: "#8b5cf6", Resolved: "#22c55e" };
const incidentPageButtonClass = "rounded-md border border-slate-200 px-2.5 py-1 text-[10px] font-medium text-slate-500 disabled:cursor-not-allowed disabled:opacity-40 dark:border-slate-700";

function IncidentStatusPanel({ demo }: { demo: MsspOverviewDemoData | null }) {
  if (!demo) return <Panel title="Incidents by Status" action={<SourceBadge provenance="UNAVAILABLE" />}><Unavailable reason="Demo workflow unavailable" /></Panel>;
  const total = demo.incidentStatuses.reduce((sum, item) => sum + item.count, 0);
  return <Panel title="Incidents by Status" action={<SourceBadge provenance="DEMO" />}><div className="grid h-full grid-cols-[8.5rem_1fr] items-center gap-2"><div className="relative h-32 w-32"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={demo.incidentStatuses} dataKey="count" nameKey="status" innerRadius={42} outerRadius={59} strokeWidth={0}>{demo.incidentStatuses.map((item) => <Cell key={item.status} fill={INCIDENT_STATUS_COLORS[item.status]} />)}</Pie><Tooltip formatter={(value) => Number(value).toLocaleString()} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-xl text-slate-800 dark:text-white">{total}</strong><span className="text-[8px] text-slate-400">incidents</span></div></div><div className="space-y-1.5">{demo.incidentStatuses.map((item) => <div key={item.status} className="flex items-center gap-1.5 text-[9px]"><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: INCIDENT_STATUS_COLORS[item.status] }} /><span className="text-slate-500">{item.status}</span><strong className="ml-auto text-slate-700 dark:text-slate-200">{item.count}</strong><span className="w-7 text-right text-slate-400">{(item.count / total * 100).toFixed(0)}%</span></div>)}</div></div></Panel>;
}

function TopIncidentClientsPanel({ demo }: { demo: MsspOverviewDemoData | null }) {
  if (!demo) return <Panel title="Top Clients by Open Incidents" action={<SourceBadge provenance="UNAVAILABLE" />}><Unavailable reason="Demo workflow unavailable" /></Panel>;
  const rows = demo.clients.filter((client) => client.openIncidents > 0).sort((left, right) => right.openIncidents - left.openIncidents).slice(0, 5); const max = rows[0]?.openIncidents || 1;
  return <Panel title="Top Clients by Open Incidents" action={<SourceBadge provenance="DEMO" />}><div className="flex h-full flex-col"><div className="space-y-2">{rows.map((client) => <div key={client.id} className="grid grid-cols-[9rem_1fr_2rem] items-center gap-2 text-[10px]"><span className="truncate font-medium text-slate-600 dark:text-slate-300" title={`${client.name} (${client.id})`}>{client.name}</span><div className="h-2 rounded-full bg-red-50 dark:bg-red-950"><div className="h-full rounded-full bg-red-400" style={{ width: `${client.openIncidents / max * 100}%` }} /></div><strong className="text-right text-slate-600 dark:text-slate-300">{client.openIncidents}</strong></div>)}</div><div className="mt-auto"><SourceNote text="Shared demo incident workflow · Not real incident attribution" /></div></div></Panel>;
}

function OpenIncidentTable({ demo }: { demo: MsspOverviewDemoData | null }) {
  const [page, setPage] = useState(1); const open = demo?.demoIncidents.filter((incident) => incident.status !== "Resolved").sort((left, right) => Date.parse(right.openedAt) - Date.parse(left.openedAt)) ?? []; const pageCount = Math.max(1, Math.ceil(open.length / 5)); const currentPage = Math.min(page, pageCount); const start = open.length ? (currentPage - 1) * 5 + 1 : 0; const end = Math.min(currentPage * 5, open.length); const rows = open.slice(start - 1, end);
  return <Panel title="Open Incidents" action={<SourceBadge provenance={demo ? "DEMO" : "UNAVAILABLE"} />}>{!demo ? <Unavailable reason="Demo workflow unavailable" /> : <><div className="overflow-x-auto"><table className="w-full min-w-[1020px] text-left text-[9px]"><thead className="border-b border-slate-200 text-slate-400 dark:border-slate-800"><tr><TableHead>Incident ID</TableHead><TableHead>Client</TableHead><TableHead>Incident Name</TableHead><TableHead>Severity</TableHead><TableHead>Status</TableHead><TableHead>Assigned To</TableHead><TableHead>Created Time</TableHead><TableHead>SLA</TableHead><TableHead>Time Elapsed</TableHead></tr></thead><tbody>{rows.map((incident) => <tr key={incident.id} className="border-b border-slate-100 dark:border-slate-800"><TableCell><strong className="whitespace-nowrap text-slate-700 dark:text-slate-200">{incident.id}</strong></TableCell><TableCell><span className="block max-w-28 truncate" title={`${incident.clientName} (${incident.clientId})`}>{incident.clientName}</span></TableCell><TableCell><span className="block max-w-40 truncate" title={incident.name}>{incident.name}</span></TableCell><TableCell><SeverityLabel severity={incident.severity} /></TableCell><TableCell><StatusPill value={incident.status} /></TableCell><TableCell>{incident.owner}</TableCell><TableCell muted>{formatUtc(incident.openedAt)}</TableCell><TableCell><SlaPill incident={incident} /></TableCell><TableCell muted>{formatDuration(incident.elapsedMinutes)}</TableCell></tr>)}</tbody></table></div><div className="mt-2 flex items-center justify-between gap-3 text-[10px] text-slate-400"><span>Showing {start}–{end} of {open.length} open incidents</span><div className="flex gap-1"><button disabled={currentPage === 1} onClick={() => setPage(Math.max(1, currentPage - 1))} className={incidentPageButtonClass}>Previous</button><button disabled={currentPage === pageCount} onClick={() => setPage(Math.min(pageCount, currentPage + 1))} className={incidentPageButtonClass}>Next</button></div></div></>}</Panel>;
}

function MitrePanel({ telemetry }: { telemetry: SocTelemetry | null }) {
  const rows = telemetry ? [...telemetry.mitre].sort((left, right) => right.count - left.count) : []; const max = Math.max(1, ...rows.map((item) => item.count)); const relevantTotal = rows.reduce((sum, item) => sum + item.count, 0);
  return <Panel title="Alerts by MITRE ATT&CK Tactic" action={<SourceBadge available={Boolean(telemetry)} />}>{!telemetry ? <Unavailable reason="Wazuh telemetry unavailable" /> : rows.length === 0 ? <Empty message="No MITRE tactic mappings observed in this period." /> : <div className="flex min-h-52 flex-col justify-center gap-2">{rows.slice(0, 8).map((item) => <div key={item.tactic} className="grid grid-cols-[minmax(6rem,1fr)_2fr_4.5rem] items-center gap-2 text-[9px]"><span className="truncate font-medium text-slate-600 dark:text-slate-300" title={item.tactic}>{item.tactic}</span><div className="h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${item.count / max * 100}%` }} /></div><span className="text-right text-slate-400">{item.count.toLocaleString()} · {relevantTotal ? (item.count / relevantTotal * 100).toFixed(1) : "0.0"}%</span></div>)}<SourceNote text="Observed mappings from Wazuh alert rules · Not ATT&CK coverage" /></div>}</Panel>;
}

function UnavailablePanel({ title, reason }: { title: string; reason: string }) { return <Panel title={title} action={<SourceBadge available={false} />}><Unavailable reason={reason} /></Panel>; }
function SourceBadge({ available, stale = false, provenance }: { available?: boolean; stale?: boolean; provenance?: "REAL" | "DEMO" | "UNAVAILABLE" }) { const state = provenance ?? (available ? "REAL" : "UNAVAILABLE"); const label = state === "REAL" ? stale ? "Real · Stale" : "Real" : state === "DEMO" ? "Demo Data" : "Unavailable"; const style = state === "REAL" ? "bg-blue-50 text-brand-blue dark:bg-blue-950" : state === "DEMO" ? "bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300" : "bg-red-50 text-red-600 dark:bg-red-950 dark:text-red-300"; return <span className={`shrink-0 rounded-full px-1.5 py-0.5 text-[7px] font-semibold uppercase tracking-wide ${style}`}>{label}</span>; }
function Unavailable({ reason }: { reason: string }) { return <div className="flex min-h-48 flex-col items-center justify-center px-4 text-center"><p className="text-2xl font-semibold text-slate-300 dark:text-slate-600">N/A</p><p className="mt-2 max-w-sm text-xs leading-5 text-slate-400">{reason}</p></div>; }
function Empty({ message }: { message: string }) { return <div className="flex min-h-48 items-center justify-center px-4 text-center text-xs text-slate-400">{message}</div>; }
function SourceNote({ text }: { text: string }) { return <p className="mt-3 border-t border-slate-100 pt-2 text-[9px] text-slate-400 dark:border-slate-800">{text}</p>; }
function TableHead({ children }: { children: React.ReactNode }) { return <th className="whitespace-nowrap px-2 py-1.5 font-semibold first:pl-0 last:pr-0">{children}</th>; }
function TableCell({ children, muted = false }: { children: React.ReactNode; muted?: boolean }) { return <td className={`px-2 py-1.5 first:pl-0 last:pr-0 ${muted ? "text-slate-500" : ""}`}>{children}</td>; }
function SeverityLabel({ severity }: { severity: Severity }) { const item = SEVERITIES.find((entry) => entry.key === severity)!; return <span className="capitalize" style={{ color: item.color }}>{severity}</span>; }
function StatusPill({ value }: { value: MsspDemoIncident["status"] }) { return <span className="whitespace-nowrap rounded-full px-1.5 py-0.5 text-[8px] font-medium text-white" style={{ backgroundColor: INCIDENT_STATUS_COLORS[value] }}>{value}</span>; }
function SlaPill({ incident }: { incident: MsspDemoIncident }) { const style = incident.slaState === "Healthy" ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300" : incident.slaState === "At Risk" ? "bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300" : "bg-red-50 text-red-600 dark:bg-red-950 dark:text-red-300"; return <span className={`whitespace-nowrap rounded-full px-1.5 py-0.5 text-[8px] font-medium ${style}`}>{incident.slaState} · {formatDuration(incident.slaTargetMinutes)}</span>; }

function MetricIcon({ name }: { name: IconName }) {
  const paths: Record<IconName, React.ReactNode> = { alerts: <><path d="M5 4h14v16H5z" /><path d="M8 8h8M8 12h8M8 16h5" /></>, critical: <><path d="M12 3 2.8 20h18.4L12 3Z" /><path d="M12 9v4M12 17h.01" /></>, high: <><path d="m5 15 7-7 7 7" /><path d="M12 8v11" /></>, incidents: <><path d="M7 3h10v4H7zM5 7h14v14H5z" /><path d="M9 12h6M9 16h4" /></>, time: <><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></>, attention: <><path d="M12 3 2.8 20h18.4L12 3Z" /><path d="M12 9v4M12 17h.01" /></> };
  return <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400" aria-hidden="true"><svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg></span>;
}
function formatDay(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleDateString([], { month: "short", day: "numeric", timeZone: "UTC" }); }
function formatUtc(value: string | null) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "UTC" }); }
function formatDuration(minutes: number) { const hours = Math.floor(minutes / 60); const remaining = minutes % 60; return hours ? `${hours}h${remaining ? ` ${remaining}m` : ""}` : `${remaining}m`; }
function PageState({ message, error = false }: { message: string; error?: boolean }) { return <div className={`flex min-h-64 items-center justify-center rounded-xl border border-dashed bg-white text-sm dark:bg-slate-900 ${error ? "border-red-200 text-red-500" : "border-slate-200 text-slate-500 dark:border-slate-800"}`}>{message}</div>; }
