"use client";

import { useState, type ReactNode } from "react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Panel } from "@/components/ui/Panel";
import type { MsspOverviewDemoData } from "@/types/mssp";

const COLORS = ["#2563eb", "#7c3aed", "#0d9488", "#f59e0b", "#e11d48"];
const ICONS = ["reports", "scheduled", "ondemand", "downloads", "category", "status"] as const;
const PAGE_SIZE = 5;

export function MsspReports({ demo }: { demo: MsspOverviewDemoData }) {
  const [page, setPage] = useState(0);
  const reports = [...demo.reports].sort((a, b) => Date.parse(b.generatedAt) - Date.parse(a.generatedAt));
  const scheduled = reports.filter((item) => item.generationMode === "scheduled").length;
  const onDemand = reports.length - scheduled;
  const downloads = reports.reduce((sum, item) => sum + item.downloadCount, 0);
  const successful = reports.filter((item) => item.status === "success").length;
  const categoryCounts = aggregate(reports.map((item) => item.category));
  const formatCounts = aggregate(reports.map((item) => item.format));
  const topCategory = categoryCounts[0];
  const successRate = successful / reports.length * 100;
  const pageCount = Math.ceil(reports.length / PAGE_SIZE);
  const visible = reports.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  const kpis = [
    { label: "Total Reports", value: reports.length.toString(), note: "demo executions", key: "total", spark: demo.reportHistory.map((item) => item.scheduled + item.onDemand) },
    { label: "Scheduled Reports", value: scheduled.toString(), note: "scheduled mode", key: "scheduled", spark: demo.reportHistory.map((item) => item.scheduled) },
    { label: "On-Demand Reports", value: onDemand.toString(), note: "on-demand mode", key: "ondemand", spark: demo.reportHistory.map((item) => item.onDemand) },
    { label: "Report Downloads", value: downloads.toString(), note: "demo consumption events", key: "downloads", spark: demo.reportHistory.map((item) => item.downloads) },
    { label: "Top Report Category", value: topCategory.label, note: `${(topCategory.count / reports.length * 100).toFixed(1)}% of reports`, key: "category", spark: [] },
    { label: "Recent Report Status", value: `${successRate.toFixed(1)}%`, note: "Successful", key: "status", spark: [] },
  ];
  return <div className="space-y-3">
    <header className="flex flex-wrap items-start justify-between gap-2"><div><h1 className="text-xl font-semibold text-slate-800 dark:text-white">Reports</h1><p className="mt-0.5 text-xs text-slate-500">Security reporting, scheduling, distribution, and generation visibility.</p></div><span className="rounded-full border border-violet-200 bg-violet-50 px-3 py-1 text-[9px] font-semibold uppercase tracking-wide text-violet-700 dark:border-violet-900 dark:bg-violet-950/40 dark:text-violet-300">Demo reporting portfolio · interface preview</span></header>
    <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{kpis.map(({ key, ...item }, index) => <Kpi key={key} {...item} icon={ICONS[index]} />)}</section>
    <section className="grid auto-rows-fr gap-3 xl:grid-cols-12"><div className="xl:col-span-4"><Panel title="Reports Over Time" action={<DemoBadge/>} className="h-full"><Timeline demo={demo}/></Panel></div><div className="xl:col-span-4"><Panel title="Reports by Category" action={<DemoBadge/>} className="h-full"><Donut items={categoryCounts} total={reports.length} centerLabel="reports"/></Panel></div><div className="xl:col-span-4"><Panel title="Top Report Templates" action={<DemoBadge/>} className="h-full"><RankBars items={demo.reportTemplates.map((template) => ({label:template.name,count:reports.filter((report)=>report.templateId===template.id).length}))}/></Panel></div></section>
    <section className="grid auto-rows-fr gap-3 xl:grid-cols-12"><div className="min-w-0 xl:col-span-5"><Panel title="Recent Reports" action={<DemoBadge/>} className="h-full"><Recent reports={visible}/><Pagination page={page} pages={pageCount} total={reports.length} onPage={setPage}/></Panel></div><div className="xl:col-span-3"><Panel title="Reports by Client" action={<DemoBadge/>} className="h-full"><RankBars items={aggregate(reports.map((item)=>item.clientName)).slice(0,7)}/></Panel></div><div className="min-w-0 xl:col-span-4"><Panel title="Scheduled Reports" action={<DemoBadge/>} className="h-full"><Schedules demo={demo}/></Panel></div></section>
    <section className="grid auto-rows-fr gap-3 xl:grid-cols-12"><div className="xl:col-span-5"><Panel title="Report Generation Summary" action={<DemoBadge/>} className="h-full"><Summary total={reports.length} successful={successful} seconds={reports.reduce((sum,item)=>sum+item.generationDurationSeconds,0)/reports.length}/></Panel></div><div className="xl:col-span-3"><Panel title="Top Report Consumers" action={<DemoBadge/>} className="h-full"><RankBars items={aggregateWeighted(reports.map((item)=>({label:item.consumer,count:item.downloadCount})))}/></Panel></div><div className="xl:col-span-4"><Panel title="Reports by Format" action={<DemoBadge/>} className="h-full"><Donut items={formatCounts} total={reports.length} centerLabel="artifacts"/></Panel></div></section>
  </div>;
}

function Kpi({label,value,note,spark,icon}:{label:string;value:string;note:string;spark:number[];icon:IconName}) { const trend=spark.length>1&&spark[0]?((spark.at(-1)!-spark[0])/spark[0]*100):null; return <article className="min-h-28 overflow-hidden rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-1"><div className="flex min-w-0 items-center gap-2"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-violet-50 text-violet-600 dark:bg-violet-950/40"><ReportIcon name={icon}/></span><p className="truncate text-[10px] font-semibold text-slate-500">{label}</p></div><DemoBadge/></div><div className="mt-2 flex items-end justify-between gap-1"><div className="min-w-0"><p title={value} className={`${label==="Top Report Category"?"truncate text-sm":"text-xl"} font-bold leading-tight text-slate-800 dark:text-white`}>{value}</p><p className="mt-1 text-[8px] text-slate-400">{trend!==null&&<span className={trend>=0?"text-emerald-600":"text-rose-500"}>{trend>=0?"+":""}{trend.toFixed(1)}% · </span>}{note}</p></div>{spark.length>1&&<Spark values={spark}/>}</div></article>; }
function Timeline({demo}:{demo:MsspOverviewDemoData}) { const data=demo.reportHistory.map((item)=>({...item,date:day(item.date)})); return <div className="flex h-56 flex-col"><div className="min-h-0 flex-1"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:8,right:8,left:-28,bottom:0}}><XAxis dataKey="date" tick={{fontSize:8}} tickLine={false} axisLine={false}/><YAxis tick={{fontSize:8}} tickLine={false} axisLine={false}/><Tooltip contentStyle={{fontSize:10,borderRadius:8}}/><Line type="monotone" dataKey="scheduled" stroke={COLORS[0]} strokeWidth={2}/><Line type="monotone" dataKey="onDemand" stroke={COLORS[1]} strokeWidth={2}/><Line type="monotone" dataKey="downloads" stroke={COLORS[2]} strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="flex justify-center gap-4 pt-2 text-[8px] text-slate-500">{[["Scheduled",COLORS[0]],["On-Demand",COLORS[1]],["Downloads",COLORS[2]]].map(([name,color])=><span key={name}><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full" style={{background:color}}/>{name}</span>)}</div></div>; }
function Donut({items,total,centerLabel}:{items:Count[];total:number;centerLabel:string}) { let offset=0; const gradient=items.map((item,index)=>{const start=offset/total*100;offset+=item.count;return `${COLORS[index%COLORS.length]} ${start}% ${offset/total*100}%`;}).join(","); return <div className="flex min-h-56 items-center justify-center gap-5"><div className="relative h-32 w-32 shrink-0 rounded-full" style={{background:`conic-gradient(${gradient})`}}><div className="absolute inset-6 flex flex-col items-center justify-center rounded-full bg-white dark:bg-slate-900"><b className="text-xl text-slate-800 dark:text-white">{total}</b><span className="text-[8px] text-slate-400">{centerLabel}</span></div></div><div className="min-w-0 flex-1 space-y-2">{items.map((item,index)=><div key={item.label} className="flex items-center gap-1 text-[9px]"><i className="h-2 w-2 shrink-0 rounded-full" style={{background:COLORS[index%COLORS.length]}}/><span className="min-w-0 flex-1 truncate text-slate-500">{item.label}</span><b>{item.count}</b><span className="w-8 text-right text-slate-400">{(item.count/total*100).toFixed(0)}%</span></div>)}</div></div>; }
function RankBars({items}:{items:Count[]}) { const max=Math.max(...items.map((item)=>item.count),1); return <div className="flex min-h-56 flex-col justify-center space-y-3">{items.slice(0,7).map((item,index)=><div key={item.label}><div className="mb-1 flex items-center gap-2 text-[9px]"><span className="w-3 text-slate-400">{index+1}</span><span title={item.label} className="min-w-0 flex-1 truncate text-slate-500">{item.label}</span><b>{item.count}</b></div><div className="ml-5 h-1.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-violet-500" style={{width:`${item.count/max*100}%`}}/></div></div>)}</div>; }
function Recent({reports}:{reports:MsspOverviewDemoData["reports"]}) { return <table className="w-full table-fixed text-left text-[9px]"><thead className="border-b border-slate-200 bg-slate-50/80 text-slate-400 dark:border-slate-800 dark:bg-slate-950/40"><tr>{[["Report Name",22],["Client",18],["Category",18],["Generated By",15],["Generated At",17],["Status",10]].map(([name,width])=><th key={name} style={{width:`${width}%`}} className="px-1.5 py-2 font-semibold">{name}</th>)}</tr></thead><tbody>{reports.map((item)=><tr key={item.id} className="border-b border-slate-100 last:border-0 dark:border-slate-800/70"><Cell value={item.reportName}/><Cell value={item.clientName}/><Cell value={item.category}/><Cell value={item.generatedBy}/><Cell value={date(item.generatedAt)}/><td className="px-1.5 py-1.5"><Status value={item.status}/></td></tr>)}</tbody></table>; }
function Schedules({demo}:{demo:MsspOverviewDemoData}) { return <table className="w-full table-fixed text-left text-[9px]"><thead className="border-b border-slate-200 bg-slate-50/80 text-slate-400 dark:border-slate-800 dark:bg-slate-950/40"><tr>{[["Report Name",32],["Frequency",14],["Next Run",24],["Recipients",15],["Status",15]].map(([name,width])=><th key={name} style={{width:`${width}%`}} className="px-1.5 py-2 font-semibold">{name}</th>)}</tr></thead><tbody>{demo.reportSchedules.map((item)=><tr key={item.id} className="border-b border-slate-100 last:border-0 dark:border-slate-800/70"><Cell value={item.reportName}/><Cell value={item.frequency}/><Cell value={date(item.nextRun)}/><Cell value={item.recipients.toString()}/><td className="px-1.5 py-1.5"><span className={`rounded-full px-1.5 py-0.5 text-[7px] font-semibold ${item.status==="Active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{item.status}</span></td></tr>)}</tbody></table>; }
function Summary({total,successful,seconds}:{total:number;successful:number;seconds:number}) { const items=[["Total Generated",total.toString(),"text-blue-600"],["Successful",successful.toString(),"text-emerald-600"],["Failed",(total-successful).toString(),"text-rose-600"],["Avg. Generation Time",duration(seconds),"text-violet-600"]]; return <div className="grid min-h-56 grid-cols-2 place-content-center gap-3">{items.map(([label,value,color])=><div key={label} className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800/50"><p className="text-[9px] text-slate-400">{label}</p><p className={`mt-1 text-xl font-bold ${color}`}>{value}</p></div>)}</div>; }
function Pagination({page,pages,total,onPage}:{page:number;pages:number;total:number;onPage:(value:number)=>void}) { const start=page*PAGE_SIZE+1,end=Math.min(total,(page+1)*PAGE_SIZE); return <div className="mt-2 flex items-center justify-between text-[9px] text-slate-400"><span>Showing {start}–{end} of {total} reports</span><div className="flex items-center gap-1"><PageButton disabled={page===0} onClick={()=>onPage(page-1)}>Previous</PageButton><span className="px-1">{page+1}/{pages}</span><PageButton disabled={page>=pages-1} onClick={()=>onPage(page+1)}>Next</PageButton></div></div>; }
function Cell({value}:{value:string}) { return <td title={value} className="truncate px-1.5 py-1.5 text-slate-500">{value}</td>; } function Status({value}:{value:"success"|"failed"}) { return <span className={`rounded-full px-1.5 py-0.5 text-[7px] font-semibold ${value==="success"?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{value==="success"?"Success":"Failed"}</span>; }
function Spark({values}:{values:number[]}) { const min=Math.min(...values),max=Math.max(...values);const points=values.map((value,index)=>`${index/(values.length-1)*68},${22-(value-min)/(max-min||1)*18}`).join(" ");return <svg viewBox="0 0 68 24" className="h-7 w-16"><polyline points={points} fill="none" stroke="#7c3aed" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
type Count={label:string;count:number}; function aggregate(values:string[]):Count[]{return [...new Set(values)].map((label)=>({label,count:values.filter((item)=>item===label).length})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label));} function aggregateWeighted(values:Count[]):Count[]{return [...new Set(values.map((item)=>item.label))].map((label)=>({label,count:values.filter((item)=>item.label===label).reduce((sum,item)=>sum+item.count,0)})).sort((a,b)=>b.count-a.count);}
function DemoBadge(){return <span className="shrink-0 rounded-full bg-violet-50 px-1.5 py-0.5 text-[7px] font-semibold uppercase tracking-wide text-violet-600 dark:bg-violet-950/50 dark:text-violet-300">Demo Data</span>;} function PageButton({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className="rounded-md border border-slate-200 px-2 py-1 text-[9px] font-medium text-slate-500 disabled:cursor-not-allowed disabled:opacity-40 dark:border-slate-700">{children}</button>;}
function date(value:string){return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Jakarta"}).format(new Date(value));} function day(value:string){return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(value));} function duration(seconds:number){const rounded=Math.round(seconds);return `${Math.floor(rounded/60)}m ${rounded%60}s`;}
type IconName=typeof ICONS[number]; function ReportIcon({name}:{name:IconName}){const paths:Record<IconName,ReactNode>={reports:<><path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 11h6M9 15h6"/></>,scheduled:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18M12 13v4l2 1"/></>,ondemand:<><path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M10 11l5 3-5 3z"/></>,downloads:<><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 19h14"/></>,category:<><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></>,status:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>};return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;}
