"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Panel } from "@/components/ui/Panel";
import type { MsspDemoServiceOffering, MsspOverviewDemoData } from "@/types/mssp";

const PAGE_SIZE = 10;
const COLORS = ["#2563eb", "#7c3aed", "#0d9488", "#f59e0b", "#e11d48", "#64748b", "#0891b2", "#9333ea", "#16a34a", "#ea580c"];
const ICONS = ["services", "active", "issues", "maintenance", "slaMet", "slaBreached"] as const;

export function MsspServices({ demo }: { demo: MsspOverviewDemoData }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All");
  const [type, setType] = useState("All");
  const [page, setPage] = useState(0);
  const openIssues = demo.serviceIssues.filter((item) => item.status !== "Resolved");
  const filtered = useMemo(() => demo.serviceOfferings.filter((service) => `${service.name} ${service.type}`.toLowerCase().includes(query.toLowerCase()) && (status === "All" || service.status === status) && (type === "All" || service.type === type)), [demo.serviceOfferings, query, status, type]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  useEffect(() => setPage((current) => Math.min(current, pages - 1)), [pages]);
  const rows = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  const start = filtered.length ? page * PAGE_SIZE + 1 : 0;
  const end = Math.min(filtered.length, (page + 1) * PAGE_SIZE);
  const kpis = [
    ["Total Services", demo.activeServices.toLocaleString(), "service assignments", "totalServices"],
    ["Active Services", demo.activeServices.toLocaleString(), "enabled subscriptions", "activeServices"],
    ["Service Issues", openIssues.length.toLocaleString(), "unresolved issues", "serviceIssues"],
    ["Maintenance Windows", demo.maintenanceWindows.length.toLocaleString(), "scheduled windows", "maintenanceWindows"],
    ["SLA Met", `${demo.sla.percentage.toFixed(1)}%`, `${demo.sla.met} of ${demo.sla.total}`, "slaPercent"],
    ["SLA Breached", demo.sla.breached.toLocaleString(), "eligible assignments", "slaBreached"],
  ] as const;
  return <div className="space-y-3">
    <header className="flex flex-wrap items-start justify-between gap-2"><div><h1 className="text-xl font-semibold text-slate-800 dark:text-white">Services</h1><p className="mt-0.5 text-xs text-slate-500">Security service catalog, health, SLA, and maintenance visibility.</p></div><span className="rounded-full border border-violet-200 bg-violet-50 px-3 py-1 text-[9px] font-semibold uppercase tracking-wide text-violet-700 dark:border-violet-900 dark:bg-violet-950/40 dark:text-violet-300">Demo service portfolio · interface preview</span></header>
    <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{kpis.map((item, index) => <Kpi key={item[0]} label={item[0]} value={item[1]} note={item[2]} icon={ICONS[index]} history={demo.serviceKpiHistory.map((point) => point[item[3]])} />)}</section>
    <section className="grid items-stretch gap-3 xl:grid-cols-12">
      <div className="min-w-0 xl:col-span-6"><Panel title="Services Overview" action={<DemoBadge />} className="h-full"><div className="mb-2 grid grid-cols-2 gap-1.5 lg:grid-cols-[minmax(9rem,1fr)_auto_auto_auto]"><label className="relative col-span-2 lg:col-span-1"><span className="sr-only">Search services</span><span className="pointer-events-none absolute inset-y-0 left-2.5 flex items-center text-slate-400"><SearchIcon /></span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder="Search services..." className={control("w-full pl-8")} /></label><Select label="Service status" value={status} onChange={(value) => { setStatus(value); setPage(0); }} values={[...new Set(demo.serviceOfferings.map((item) => item.status))]} /><Select label="Service type" value={type} onChange={(value) => { setType(value); setPage(0); }} values={[...new Set(demo.serviceOfferings.map((item) => item.type))]} /><button disabled title="Export is not available in demo mode" className={control("inline-flex cursor-not-allowed items-center justify-center gap-1 opacity-55")}><ExportIcon />Export</button></div>
        <div className="rounded-lg border border-slate-100 dark:border-slate-800"><table className="w-full table-fixed text-left text-[9px]"><thead className="border-b border-slate-200 bg-slate-50/80 text-slate-400 dark:border-slate-800 dark:bg-slate-950/40"><tr>{[["Service Name","w-[17%]"],["Service Type","w-[15%]"],["Clients","w-[7%]"],["Status","w-[10%]"],["Health","w-[9%]"],["SLA","w-[8%]"],["MTTR","w-[8%]"],["Last Activity","w-[17%]"],["","w-[9%]"]].map(([heading,width]) => <th key={heading || "action"} className={`${width} px-1.5 py-2 font-semibold`}>{heading}</th>)}</tr></thead><tbody>{rows.map((service) => <ServiceRow key={service.id} service={service} />)}{!rows.length && <tr><td colSpan={9} className="py-10 text-center text-xs text-slate-400">No demo services match these filters.</td></tr>}</tbody></table></div>
        <div className="mt-2 flex items-center justify-between text-[9px] text-slate-400"><span>Showing {start}–{end} of {filtered.length} services</span><div className="flex items-center gap-1"><PageButton disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</PageButton><span className="px-1">{page + 1}/{pages}</span><PageButton disabled={page >= pages - 1} onClick={() => setPage(page + 1)}>Next</PageButton></div></div></Panel></div>
      <div className="min-w-0 xl:col-span-3"><Panel title="Service Health Over Time" action={<DemoBadge />} className="h-full"><HealthChart demo={demo} /></Panel></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:col-span-3 xl:grid-cols-1"><Panel title="Services by Type" action={<DemoBadge />} className="h-full"><TypeDonut demo={demo} /></Panel><Panel title="Services by Status" action={<DemoBadge />} className="h-full"><StatusBars services={demo.serviceOfferings} /></Panel></div>
    </section>
    <section className="grid items-stretch gap-3 xl:grid-cols-12"><div className="xl:col-span-3"><Panel title="SLA Performance by Service" action={<DemoBadge />} className="h-full"><SlaList services={demo.serviceOfferings} /></Panel></div><div className="min-w-0 xl:col-span-5"><Panel title="Top Service Issues" action={<DemoBadge />} className="h-full"><Issues issues={openIssues} /></Panel></div><div className="min-w-0 xl:col-span-4"><Panel title="Upcoming Maintenance Windows" action={<DemoBadge />} className="h-full"><Maintenance demo={demo} /></Panel></div></section>
  </div>;
}

function Kpi({ label, value, note, icon, history }: { label:string; value:string; note:string; icon:IconName; history:number[] }) { const first=history[0], last=history.at(-1)??first, trend=first?(last-first)/first*100:0; return <article className="min-h-28 overflow-hidden rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-1"><div className="flex min-w-0 items-center gap-2"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-blue-600 dark:bg-blue-950/40"><Icon name={icon}/></span><p className="truncate text-[10px] font-semibold text-slate-500">{label}</p></div><DemoBadge/></div><div className="mt-1.5 flex items-end justify-between gap-1"><div><p className="text-xl font-bold leading-none text-slate-800 dark:text-white">{value}</p><p className={`mt-1 text-[8px] ${trend<0?"text-rose-500":"text-emerald-600"}`}>{trend>=0?"+":""}{trend.toFixed(1)}% · {note}</p></div><Spark values={history}/></div></article>; }
function ServiceRow({service}:{service:MsspDemoServiceOffering}) { return <tr className="border-b border-slate-100 last:border-0 dark:border-slate-800/70"><Cell title={service.name} strong>{service.name}</Cell><Cell title={service.type}>{service.type}</Cell><Cell>{service.clients}</Cell><Cell><Status value={service.status}/></Cell><Cell><span className={service.healthScore<85?"text-amber-600":"text-emerald-600"}>{service.healthScore}/100</span></Cell><Cell>{service.slaPercent.toFixed(1)}%</Cell><Cell>{service.mttrMinutes===null?"—":`${service.mttrMinutes}m`}</Cell><Cell title={date(service.lastActivity)}>{date(service.lastActivity)}</Cell><Cell><button disabled title="Read-only demo record" className="rounded border border-slate-200 px-1.5 py-0.5 text-[8px] text-slate-400 dark:border-slate-700">View</button></Cell></tr>; }
function Cell({children,title,strong=false}:{children:ReactNode;title?:string;strong?:boolean}) { return <td title={title} className={`truncate px-1.5 py-1.5 ${strong?"font-medium text-slate-700 dark:text-slate-200":"text-slate-500"}`}>{children}</td>; }
function HealthChart({demo}:{demo:MsspOverviewDemoData}) { const names=demo.serviceHealthHistory[0]?.scores.map((item)=>item.serviceName)??[]; const data=demo.serviceHealthHistory.map((item)=>({date:day(item.date),...Object.fromEntries(item.scores.map((score)=>[score.serviceName,score.score]))})); return <div className="flex h-full min-h-[19rem] flex-col"><div className="min-h-0 flex-1"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:12,right:8,left:-24,bottom:2}}><XAxis dataKey="date" tick={{fontSize:8}} tickLine={false} axisLine={false}/><YAxis domain={[70,100]} tick={{fontSize:8}} tickLine={false} axisLine={false}/><Tooltip contentStyle={{fontSize:10,borderRadius:8}}/>{names.map((name,index)=><Line key={name} type="monotone" dataKey={name} stroke={COLORS[index]} strokeWidth={1.8} dot={false}/>)}</LineChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-1 border-t border-slate-100 pt-2 text-[8px] text-slate-500 dark:border-slate-800">{names.map((name,index)=><span key={name} className="truncate"><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full" style={{background:COLORS[index]}}/>{name}</span>)}</div></div>; }
function TypeDonut({demo}:{demo:MsspOverviewDemoData}) { const total=demo.servicesByType.reduce((sum,item)=>sum+item.count,0); let offset=0; const gradient=demo.servicesByType.map((item,index)=>{const start=offset/total*100;offset+=item.count;return `${COLORS[index]} ${start}% ${offset/total*100}%`;}).join(","); return <div className="flex items-center gap-3"><div className="relative h-24 w-24 shrink-0 rounded-full" style={{background:`conic-gradient(${gradient})`}}><div className="absolute inset-[18px] flex flex-col items-center justify-center rounded-full bg-white dark:bg-slate-900"><b className="text-lg text-slate-800 dark:text-white">{total}</b><span className="text-[7px] text-slate-400">assignments</span></div></div><div className="min-w-0 flex-1 space-y-1">{demo.servicesByType.map((item,index)=><div key={item.type} className="flex items-center gap-1 text-[8px]"><i className="h-1.5 w-1.5 shrink-0 rounded-full" style={{background:COLORS[index]}}/><span className="min-w-0 flex-1 truncate text-slate-500">{item.type}</span><b>{item.count}</b><span className="w-7 text-right text-slate-400">{(item.count/total*100).toFixed(0)}%</span></div>)}</div></div>; }
function StatusBars({services}:{services:MsspDemoServiceOffering[]}) { return <div className="space-y-2.5 py-1">{(["Active","Warning","Maintenance"] as const).map((value)=>{const count=services.filter((item)=>item.status===value).length;return <Bar key={value} label={value} count={count} percent={count/services.length*100} color={value==="Active"?"bg-emerald-500":value==="Warning"?"bg-amber-500":"bg-blue-500"}/>})}<p className="border-t border-slate-100 pt-2 text-[8px] text-slate-400 dark:border-slate-800">{services.length} demo service offerings</p></div>; }
function Bar({label,count,percent,color}:{label:string;count:number;percent:number;color:string}) { return <div><div className="mb-1 flex justify-between text-[9px]"><span className="text-slate-500">{label}</span><b>{count}</b></div><div className="h-1.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${color}`} style={{width:`${percent}%`}}/></div></div>; }
function SlaList({services}:{services:MsspDemoServiceOffering[]}) { return <div className="space-y-2">{services.map((item)=><div key={item.id}><div className="mb-0.5 flex gap-2 text-[8px]"><span className="min-w-0 flex-1 truncate text-slate-500">{item.name}</span><b>{item.slaPercent.toFixed(1)}%</b></div><div className="h-1.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${item.slaPercent>=95?"bg-emerald-500":item.slaPercent>=90?"bg-amber-500":"bg-rose-500"}`} style={{width:`${item.slaPercent}%`}}/></div></div>)}</div>; }
function Issues({issues}:{issues:MsspOverviewDemoData["serviceIssues"]}) { return <Table heads={["Service","Issue","Severity","Affects","Status","Detected"]} widths={[20,25,12,10,15,18]} rows={issues.slice(0,6).map((item)=>[item.serviceName,item.issue,<Severity key="s" value={item.severity}/>,`${item.affectedClients} clients`,<span key="st" className="text-amber-600">{item.status}</span>,date(item.detectedAt)])} footer={`${issues.length} unresolved demo service issues`}/>; }
function Maintenance({demo}:{demo:MsspOverviewDemoData}) { return <Table heads={["Service","Start","End","Affects"]} widths={[31,25,25,19]} rows={demo.maintenanceWindows.slice(0,6).map((item)=>[item.serviceName,date(item.startAt),date(item.endAt),`${item.affectedClients} clients`])} footer="Deterministic read-only maintenance schedule"/>; }
function Table({heads,widths,rows,footer}:{heads:string[];widths:number[];rows:ReactNode[][];footer:string}) { return <div><table className="w-full table-fixed text-left text-[9px]"><thead className="border-b border-slate-200 text-slate-400 dark:border-slate-800"><tr>{heads.map((head,index)=><th key={head} className="px-1 py-2 font-semibold" style={{width:`${widths[index]}%`}}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-b border-slate-100 last:border-0 dark:border-slate-800/70">{row.map((cell,cellIndex)=><Cell key={cellIndex} title={typeof cell==="string"?cell:undefined}>{cell}</Cell>)}</tr>)}</tbody></table><p className="mt-2 border-t border-slate-100 pt-2 text-[8px] text-slate-400 dark:border-slate-800">{footer}</p></div>; }
function Select({label,value,onChange,values}:{label:string;value:string;onChange:(value:string)=>void;values:string[]}) { return <select aria-label={label} value={value} onChange={(event)=>onChange(event.target.value)} className={control()}><option value="All">All {label.replace("Service ","")}</option>{values.map((item)=><option key={item}>{item}</option>)}</select>; }
function Spark({values}:{values:number[]}) { const min=Math.min(...values),max=Math.max(...values);const points=values.map((value,index)=>`${index/(values.length-1)*68},${22-(value-min)/(max-min||1)*18}`).join(" ");return <svg viewBox="0 0 68 24" className="h-7 w-16"><polyline points={points} fill="none" stroke="#2563eb" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
function DemoBadge(){return <span className="shrink-0 rounded-full bg-violet-50 px-1.5 py-0.5 text-[7px] font-semibold uppercase tracking-wide text-violet-600 dark:bg-violet-950/50 dark:text-violet-300">Demo Data</span>;}
function Status({value}:{value:MsspDemoServiceOffering["status"]}){return <span className={`rounded-full px-1.5 py-0.5 text-[7px] font-semibold ${value==="Active"?"bg-emerald-50 text-emerald-700":value==="Warning"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700"}`}>{value}</span>;}
function Severity({value}:{value:MsspOverviewDemoData["serviceIssues"][number]["severity"]}){return <span className={`rounded-full px-1.5 py-0.5 text-[7px] font-semibold ${value==="Critical"?"bg-rose-50 text-rose-700":value==="High"?"bg-orange-50 text-orange-700":value==="Medium"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{value}</span>;}
function PageButton({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className="rounded-md border border-slate-200 px-2 py-1 text-[9px] font-medium text-slate-500 disabled:cursor-not-allowed disabled:opacity-40 dark:border-slate-700">{children}</button>;}
function date(value:string){return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Jakarta"}).format(new Date(value));} function day(value:string){return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(value));} function control(extra=""){return `h-8 rounded-md border border-slate-200 bg-white px-2 text-[9px] text-slate-600 outline-none focus:border-blue-400 dark:border-slate-700 dark:bg-slate-900 ${extra}`;}
type IconName=typeof ICONS[number]; function Icon({name}:{name:IconName}){const p:Record<IconName,ReactNode>={services:<><path d="M4 6h16v5H4zM4 14h16v5H4z"/><path d="M7 8.5h.01M7 16.5h.01"/></>,active:<><circle cx="12" cy="12" r="9"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,issues:<><path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v4M12 17h.01"/></>,maintenance:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/></>,slaMet:<><circle cx="12" cy="12" r="9"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,slaBreached:<><circle cx="12" cy="12" r="9"/><path d="M9 9l6 6M15 9l-6 6"/></>};return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>;}
function SearchIcon(){return <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7"/><path d="m16 16 4 4"/></svg>;} function ExportIcon(){return <svg viewBox="0 0 24 24" className="h-3 w-3" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 19h14"/></svg>;}
