"use client";

import { useMemo, useState, type ReactNode } from "react";
import { CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import worldMap from "@svg-maps/world";
import { Panel } from "@/components/ui/Panel";
import type { MsspDemoClient, MsspOverviewDemoData } from "@/types/mssp";

const CLIENT_COLUMNS = ["Client Name", "Industry", "Services", "Risk Score", "Open Alerts", "Open Incidents", "SLA Status", "Status", "Last Activity", "Actions"] as const;
const RISK_LEVELS = ["Low", "Medium", "High", "Critical"] as const;
const RISK_COLORS = { Low: "#22c55e", Medium: "#eab308", High: "#f97316", Critical: "#ef4444" } as const;
const PAGE_SIZE = 10;
type WorldMapGeometry = { viewBox: string; locations: Array<{ id: string; name: string; path: string }> };
const worldGeometry = worldMap as WorldMapGeometry;

export function MsspClients({ demo }: { demo: MsspOverviewDemoData }) {
  const active = demo.clients.filter((client) => client.status === "Active").length;
  const inactive = demo.clients.filter((client) => client.status === "Inactive").length;
  const atRisk = demo.clients.filter((client) => client.riskLevel === "High" || client.riskLevel === "Critical").length;
  const slaMet = demo.clients.filter((client) => client.slaStatus === "Met").length;
  const averageRisk = demo.clients.reduce((total, client) => total + client.riskScore, 0) / demo.clients.length;
  const history = demo.clientKpiHistory;
  const kpis = [
    { title: "Total Clients", value: demo.clients.length, detail: "Shared demo portfolio", icon: "clients" as const, history: history.map((item) => item.totalClients) },
    { title: "Active Clients", value: active, detail: "Active lifecycle", icon: "active" as const, history: history.map((item) => item.activeClients) },
    { title: "At Risk Clients", value: atRisk, detail: "High or Critical risk", icon: "risk" as const, history: history.map((item) => item.atRiskClients) },
    { title: "Inactive Clients", value: inactive, detail: "Inactive lifecycle", icon: "inactive" as const, history: history.map((item) => item.inactiveClients) },
    { title: "Client SLA Met", value: `${(slaMet / demo.clients.length * 100).toFixed(1)}%`, detail: `${slaMet} of ${demo.clients.length} clients`, icon: "sla" as const, history: history.map((item) => item.slaPercent) },
    { title: "Avg. Risk Score", value: averageRisk.toFixed(1), detail: "Demo scale · 0–100", icon: "score" as const, history: history.map((item) => item.averageRisk) },
  ];

  return <div className="space-y-3">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold text-slate-800 dark:text-white">Clients</h1><p className="mt-1 text-sm text-slate-500">Client monitoring, service visibility, and risk overview.</p></div><span className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-[10px] font-semibold uppercase tracking-wide text-amber-700 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300">Demo client portfolio · Temporary interface preview</span></header>
    <section className="grid gap-2.5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{kpis.map((item) => <ClientKpiCard key={item.title} {...item} />)}</section>
    <section className="grid gap-4 xl:grid-cols-12"><div className="min-w-0 xl:col-span-8"><ClientsOverviewTable clients={demo.clients} /></div><div className="grid gap-4 sm:grid-cols-2 xl:col-span-4 xl:grid-cols-1"><ClientsRiskPanel clients={demo.clients} /><TopClientsPanel clients={demo.clients} /></div></section>
    <section className="grid gap-3 lg:grid-cols-10"><div className="lg:col-span-3"><ClientActivityPanel demo={demo} /></div><div className="lg:col-span-3"><ServiceAdoptionPanel clients={demo.clients} /></div><div className="lg:col-span-4"><ClientGeographyPanel clients={demo.clients} /></div></section>
  </div>;
}

type IconName = "clients" | "active" | "risk" | "inactive" | "sla" | "score";
function ClientKpiCard({ title, value, detail, icon, history }: { title: string; value: number | string; detail: string; icon: IconName; history: number[] }) { const trend = percentageChange(history); const chartData = history.map((point, index) => ({ index, value: point })); return <article className="relative min-h-28 overflow-hidden rounded-xl border border-slate-200 bg-white p-3 shadow-sm shadow-slate-200/30 dark:border-slate-800 dark:bg-slate-900 dark:shadow-none"><div className="flex items-start justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-amber-50 text-amber-600 dark:bg-amber-950 dark:text-amber-300" aria-hidden="true"><ClientIcon name={icon} /></span><p className="truncate text-[11px] font-semibold text-slate-500">{title}</p></div><DemoBadge /></div><div className="mt-1.5 grid grid-cols-[1fr_4.5rem] items-end gap-1"><div><p className="text-xl font-bold leading-none text-slate-800 dark:text-white">{typeof value === "number" ? value.toLocaleString() : value}</p><p className={`mt-1 text-[9px] font-medium ${trend >= 0 ? "text-emerald-600" : "text-red-500"}`}>{trend >= 0 ? "↑" : "↓"} {Math.abs(trend).toFixed(1)}% <span className="font-normal text-slate-400">vs 7 days</span></p><p className="mt-0.5 truncate text-[8px] text-slate-400">{detail}</p></div><div className="h-10"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><Line type="monotone" dataKey="value" stroke="#2563eb" strokeWidth={1.8} dot={false} /></LineChart></ResponsiveContainer></div></div></article>; }

function ClientsOverviewTable({ clients }: { clients: MsspDemoClient[] }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [risk, setRisk] = useState("all"); const [page, setPage] = useState(1);
  const filtered = useMemo(() => clients.filter((client) => { const term = query.trim().toLowerCase(); return (!term || client.name.toLowerCase().includes(term) || client.industry.toLowerCase().includes(term)) && (status === "all" || client.status === status) && (risk === "all" || client.riskLevel === risk); }), [clients, query, status, risk]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const currentPage = Math.min(page, pageCount); const rows = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);
  const update = (setter: (value: string) => void) => (value: string) => { setter(value); setPage(1); };
  return <Panel title="Clients Overview" action={<DemoBadge />}><div className="mb-2 flex flex-wrap items-center justify-end gap-1.5"><label className="relative min-w-40 flex-1 sm:max-w-[15rem]"><span className="sr-only">Search clients</span><span className="pointer-events-none absolute inset-y-0 left-2.5 flex items-center text-slate-400" aria-hidden="true"><SearchIcon /></span><input value={query} onChange={(event) => update(setQuery)(event.target.value)} placeholder="Search clients" className={controlClass("pl-7")} /></label><select value={status} onChange={(event) => update(setStatus)(event.target.value)} aria-label="Client status" className={controlClass()}><option value="all">All Status</option><option>Active</option><option>Inactive</option><option>Onboarding</option></select><select value={risk} onChange={(event) => update(setRisk)(event.target.value)} aria-label="Client risk level" className={controlClass()}><option value="all">All Risk Levels</option>{RISK_LEVELS.map((level) => <option key={level}>{level}</option>)}</select><button disabled className={controlClass("inline-flex items-center gap-1 font-medium")} title="Export is not available in demo mode"><ExportIcon /> Export</button></div>
    <div className="overflow-x-auto rounded-lg border border-slate-100 dark:border-slate-800"><table className="w-full min-w-[1040px] text-left text-[9px]"><thead className="border-b border-slate-200 bg-slate-50/80 text-slate-400 dark:border-slate-800 dark:bg-slate-950/40"><tr>{CLIENT_COLUMNS.map((heading) => <th key={heading} className="whitespace-nowrap px-2 py-1.5 font-semibold">{heading}</th>)}</tr></thead><tbody>{rows.length ? rows.map((client) => <ClientRow key={client.id} client={client} />) : <tr><td colSpan={CLIENT_COLUMNS.length} className="py-12 text-center text-xs text-slate-400">No demo clients match these filters.</td></tr>}</tbody></table></div>
    <div className="mt-3 flex items-center justify-between gap-3 text-[10px] text-slate-400"><span>{filtered.length} clients · Page {currentPage} of {pageCount}</span><div className="flex gap-1"><button disabled={currentPage === 1} onClick={() => setPage((value) => Math.max(1, value - 1))} className={pageButtonClass}>Previous</button><button disabled={currentPage === pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))} className={pageButtonClass}>Next</button></div></div></Panel>;
}

function ClientRow({ client }: { client: MsspDemoClient }) { return <tr className="border-b border-slate-100 dark:border-slate-800"><td className="whitespace-nowrap px-2 py-1 font-medium" title={client.id}>{client.name}</td><td className="whitespace-nowrap px-2 py-1 text-slate-500">{client.industry}</td><td className="px-2 py-1">{client.services} services</td><td className="px-2 py-1"><RiskBadge client={client} /></td><td className="px-2 py-1">{client.openAlerts}</td><td className="px-2 py-1">{client.openIncidents}</td><td className="px-2 py-1"><StatusBadge value={client.slaStatus} /></td><td className="px-2 py-1"><StatusBadge value={client.status} /></td><td className="whitespace-nowrap px-2 py-1 text-slate-500">{formatUtc(client.lastActivity)}</td><td className="px-2 py-1"><button disabled title="Client detail is not available in demo mode" className="rounded border border-slate-200 px-1.5 py-0.5 text-[8px] text-slate-400 disabled:cursor-not-allowed dark:border-slate-700">View</button></td></tr>; }

function ClientsRiskPanel({ clients }: { clients: MsspDemoClient[] }) { const rows = [...RISK_LEVELS].reverse().map((level) => ({ name: level, value: clients.filter((client) => client.riskLevel === level).length, color: RISK_COLORS[level] })).filter((row) => row.value); return <Panel title="Clients by Risk Level" action={<DemoBadge />}><Donut rows={rows} total={clients.length} label="clients" /></Panel>; }
function TopClientsPanel({ clients }: { clients: MsspDemoClient[] }) { const rows = clients.slice().sort((left, right) => right.openAlerts - left.openAlerts).slice(0, 5); const max = rows[0]?.openAlerts || 1; return <Panel title="Top Clients by Open Alerts" action={<DemoBadge />}><div className="flex min-h-36 flex-col justify-center gap-2">{rows.map((client) => <div key={client.id} className="grid grid-cols-[7rem_1fr_1.5rem] items-center gap-2 text-[9px]"><span className="truncate font-medium text-slate-600 dark:text-slate-300" title={`${client.name} (${client.id})`}>{client.name}</span><div className="h-2 rounded-full bg-red-50 dark:bg-red-950"><div className="h-full rounded-full bg-red-400" style={{ width: `${client.openAlerts / max * 100}%` }} /></div><span className="text-right font-semibold text-slate-500">{client.openAlerts}</span></div>)}<SourceNote text="Demo workflow counts · Not Wazuh attribution" /></div></Panel>; }

function ClientActivityPanel({ demo }: { demo: MsspOverviewDemoData }) { const rows = demo.clientKpiHistory.map((item) => ({ ...item, day: new Date(item.date).toLocaleDateString([], { month: "short", day: "numeric", timeZone: "UTC" }) })); return <Panel title="Client Activity Timeline (7 Days)" action={<DemoBadge />}><div className="h-48"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{ left: -25, right: 5, top: 4, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="day" tick={{ fontSize: 8 }} /><YAxis allowDecimals={false} tick={{ fontSize: 8 }} /><Tooltip /><Legend iconType="circle" iconSize={6} wrapperStyle={{ fontSize: 9 }} /><Line type="monotone" dataKey="newClients" name="New Clients" stroke="#22c55e" strokeWidth={1.8} dot={false} /><Line type="monotone" dataKey="openAlerts" name="Open Alerts" stroke="#f97316" strokeWidth={1.8} dot={false} /><Line type="monotone" dataKey="openIncidents" name="Open Incidents" stroke="#ef4444" strokeWidth={1.8} dot={false} /></LineChart></ResponsiveContainer></div><SourceNote text="Deterministic demo client workflow · Not Wazuh telemetry" /></Panel>; }
function ServiceAdoptionPanel({ clients }: { clients: MsspDemoClient[] }) { const services = Array.from(new Set(clients.flatMap((client) => client.serviceTypes))).map((name) => { const value = clients.filter((client) => client.serviceTypes.includes(name)).length; return { name, value, percentage: value / clients.length * 100 }; }).sort((a, b) => b.value - a.value); return <Panel title="Clients by Service Adoption" action={<DemoBadge />}><div className="min-h-48"><div className="grid grid-cols-[1fr_4rem_1.2fr] gap-2 border-b border-slate-100 pb-1 text-[8px] font-semibold uppercase tracking-wide text-slate-400 dark:border-slate-800"><span>Service</span><span className="text-center">Clients Using</span><span>Adoption</span></div><div className="space-y-2 pt-2">{services.map((service) => <div key={service.name} className="grid grid-cols-[1fr_4rem_1.2fr] items-center gap-2 text-[9px]"><span className="truncate text-slate-500" title={service.name}>{service.name}</span><span className="text-center font-semibold text-slate-700 dark:text-slate-200">{service.value}</span><div className="flex items-center gap-1.5"><div className="h-1.5 flex-1 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-blue-500" style={{ width: `${service.percentage}%` }} /></div><span className="w-7 text-right text-slate-400">{service.percentage.toFixed(0)}%</span></div></div>)}</div><SourceNote text="Clients assigned per shared demo service category" /></div></Panel>; }
function ClientGeographyPanel({ clients }: { clients: MsspDemoClient[] }) { const locations = Array.from(new Set(clients.map((client) => client.city))).map((city) => ({ name: city, value: clients.filter((client) => client.city === city).length })).sort((a, b) => b.value - a.value); return <Panel title="Client Geographic Distribution" action={<DemoBadge />}><div className="grid min-h-48 grid-cols-[1.45fr_1fr] items-center gap-3"><div className="relative h-40 overflow-hidden rounded-lg bg-slate-50 dark:bg-slate-950/40"><svg aria-label="World map highlighting the fictional demo client country" className="h-full w-full" preserveAspectRatio="xMidYMid meet" role="img" viewBox={worldGeometry.viewBox}>{worldGeometry.locations.map((location) => <path key={location.id} d={location.path} fill={location.id === "id" ? "#2563eb" : "#e2e8f0"} stroke="#ffffff" strokeWidth="0.7"><title>{location.id === "id" ? `Indonesia: ${clients.length} demo clients` : location.name}</title></path>)}</svg><span className="absolute bottom-1 left-1 rounded bg-white/80 px-1 text-[7px] text-slate-400 dark:bg-slate-900/80">Map geometry CC BY 4.0</span></div><div><div className="mb-2 flex items-center justify-between border-b border-slate-100 pb-1 text-[9px] dark:border-slate-800"><span className="flex items-center gap-1.5 font-medium text-slate-600 dark:text-slate-300"><span className="h-2 w-2 rounded-full bg-blue-600" />Indonesia</span><strong>{clients.length}</strong></div><div className="space-y-1.5">{locations.map((location) => <div key={location.name} className="flex justify-between text-[9px] text-slate-500"><span>{location.name}</span><span className="font-medium text-slate-700 dark:text-slate-200">{location.value}</span></div>)}</div></div></div><SourceNote text="Fictional client locations · Not telemetry geography" /></Panel>; }

function Donut({ rows, total, label }: { rows: Array<{ name: string; value: number; color: string }>; total: number; label: string }) { return <div className="grid min-h-40 grid-cols-[9.5rem_1fr] items-center gap-3"><div className="relative h-36 w-36"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="value" nameKey="name" innerRadius={47} outerRadius={66} strokeWidth={0}>{rows.map((row) => <Cell key={row.name} fill={row.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-2xl font-bold text-slate-800 dark:text-white">{total}</span><span className="text-[9px] text-slate-400">{label}</span></div></div><div className="space-y-2">{rows.map((row) => <div key={row.name} className="flex items-center gap-2 text-[10px]"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: row.color }} /><span className="text-slate-500">{row.name}</span><span className="ml-auto font-semibold text-slate-700 dark:text-slate-200">{row.value}</span><span className="w-8 text-right text-slate-400">{(row.value / total * 100).toFixed(0)}%</span></div>)}</div></div>; }
function RiskBadge({ client }: { client: MsspDemoClient }) { return <span className="inline-flex items-center gap-1 whitespace-nowrap rounded-full bg-slate-100 px-2 py-0.5 dark:bg-slate-800"><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: RISK_COLORS[client.riskLevel] }} />{client.riskScore} · {client.riskLevel}</span>; }
function StatusBadge({ value }: { value: string }) { const positive = value === "Active" || value === "Met"; const negative = value === "Inactive" || value === "Breached"; return <span className={`whitespace-nowrap rounded-full px-2 py-0.5 text-[9px] font-medium ${positive ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300" : negative ? "bg-red-50 text-red-600 dark:bg-red-950 dark:text-red-300" : "bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300"}`}>{value}</span>; }
function DemoBadge() { return <span className="shrink-0 rounded-full bg-amber-50 px-1.5 py-0.5 text-[7px] font-semibold uppercase tracking-wide text-amber-700 dark:bg-amber-950 dark:text-amber-300">Demo Data</span>; }
function SourceNote({ text }: { text: string }) { return <p className="mt-3 border-t border-slate-100 pt-2 text-[9px] text-slate-400 dark:border-slate-800">{text}</p>; }
function controlClass(extra = "") { return `h-8 rounded-md border border-slate-200 bg-white px-2.5 text-[10px] text-slate-500 outline-none focus:border-blue-400 disabled:cursor-not-allowed disabled:bg-slate-50 disabled:text-slate-400 dark:border-slate-700 dark:bg-slate-800 dark:disabled:bg-slate-800 ${extra}`; }
const pageButtonClass = "rounded-md border border-slate-200 px-2.5 py-1 text-[10px] font-medium text-slate-500 disabled:cursor-not-allowed disabled:opacity-40 dark:border-slate-700";
function formatUtc(value: string) { return new Date(value).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "UTC" }); }
function percentageChange(values: number[]) { const first = values[0] ?? 0; const last = values.at(-1) ?? first; return first === 0 ? 0 : (last - first) / first * 100; }

function ClientIcon({ name }: { name: IconName }) { const paths: Record<IconName, ReactNode> = { clients: <><circle cx="8" cy="8" r="3" /><circle cx="16" cy="9" r="2.5" /><path d="M3 19c.5-3 2.2-5 5-5s4.5 2 5 5M13 15c3.6-1.2 6.6.7 7 4" /></>, active: <><circle cx="12" cy="12" r="9" /><path d="m8.5 12 2.2 2.2 4.8-5" /></>, risk: <><path d="M12 3 2.8 20h18.4L12 3Z" /><path d="M12 9v4M12 17h.01" /></>, inactive: <><circle cx="12" cy="12" r="9" /><path d="M8.5 12h7" /></>, sla: <><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></>, score: <><path d="M4 19V9M10 19V5M16 19v-7M22 19V8" /></> }; return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>; }
function SearchIcon() { return <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7" /><path d="m16 16 4 4" /></svg>; }
function ExportIcon() { return <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 19h14" /></svg>; }
