"use client";
import Link from "next/link";
import { Topbar } from "@/components/layout/Topbar";
import { Panel, PanelEmpty, PanelError, PanelLoading } from "@/components/ui/Panel";
import { useSidebarToggle } from "@/context/sidebar-context";
import { useApiResult } from "@/hooks/useApiResult";
import type { ThreatIntelligenceOverviewData } from "@/types/threat-intel";

export default function ThreatIntelligencePage(){const openSidebar=useSidebarToggle();const state=useApiResult<ThreatIntelligenceOverviewData>("/api/ciso/threat-intelligence");return <><Topbar title="Threat Intelligence Detail" subtitle="External intelligence observations and provider validation state" onMenuClick={openSidebar}/><main className="flex-1 space-y-4 bg-slate-50 p-4 sm:p-6 dark:bg-slate-950"><Link href="/dashboard/ciso" className="text-sm text-brand-blue hover:underline">← Back to CISO dashboard</Link><Panel title="Provider Health">{state.phase==="loading"?<PanelLoading/>:state.phase==="error"?<PanelError message={state.message} onRetry={state.reload}/>:state.phase==="ready"?<div className="grid gap-3 sm:grid-cols-3">{Object.entries(state.data.providers).map(([key,p])=><div key={key} className="rounded border border-slate-200 p-3 text-xs dark:border-slate-800"><b>{p.name}</b><div className="mt-1 capitalize text-slate-500">{p.status}</div><div className="text-slate-400">{p.detail}</div></div>)}</div>:<PanelEmpty/>}</Panel>
<Panel title="Observed IOCs" action={<span className="text-xs text-slate-400">{state.phase==="ready"&&state.data.observedAt?`${state.data.availability==="cached"?"Cached from":"Observed"} ${new Date(state.data.observedAt).toLocaleString()}`:"Last 7 days"}</span>}>{state.phase==="loading"&&<PanelLoading/>}{state.phase==="error"&&<PanelError message={state.message} onRetry={state.reload}/>} {state.phase==="ready"&&(state.data.availability==="unavailable"?<PanelError message="ThreatFox source unavailable; enrichment is not treated as feed data." onRetry={state.reload}/>:state.data.observedIocs.length===0?<PanelEmpty message="No eligible IOCs. Enrichment providers are not validated."/>:<div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><thead className="border-b text-slate-500"><tr><th className="py-2">Indicator</th><th>Type</th><th>Provider</th><th>Confidence</th><th>Observed</th><th>Malware</th></tr></thead><tbody className="divide-y dark:divide-slate-800">{state.data.observedIocs.map(x=><tr key={x.id}><td className="max-w-sm break-all py-3 font-mono">{x.indicator}</td><td>{x.iocType}</td><td>{x.provider}</td><td>{x.confidence===null?"Unavailable":`${x.confidence}%`}</td><td>{x.observedAt?new Date(x.observedAt).toLocaleString():"Unavailable"}</td><td>{x.malware||"Unclassified"}</td></tr>)}</tbody></table></div>)}</Panel></main></>}
