import { Download, MoreVertical, FileText, FilePieChart, Database, Activity, ShieldAlert, ArrowRight } from "lucide-react";

const reports = [
  { id: 1, name: "Weekly Security Operations Summary", category: "Security Operations", type: "Scheduled", by: "Fandi Juncrry", time: "May 19, 2025 09:15 AM", icon: Activity },
  { id: 2, name: "Incident Summary Report", category: "Incident & Case Management", type: "Scheduled", by: "Andi Wijaya", time: "May 19, 2025 08:30 AM", icon: ShieldAlert },
  { id: 3, name: "Top Threats & Indicators Report", category: "Threat Intelligence", type: "On-Demand", by: "Rizky Pratama", time: "May 19, 2025 07:45 AM", icon: Database },
  { id: 4, name: "Compliance Posture Report (UU PDP)", category: "Compliance & Audit", type: "Scheduled", by: "Siti Aisyah", time: "May 18, 2025 06:10 PM", icon: FilePieChart },
  { id: 5, name: "Case Management Overview", category: "Incident & Case Management", type: "Scheduled", by: "Fandi Juncrry", time: "May 18, 2025 05:00 PM", icon: FileText },
];

export function RecentReports() {
  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-4 shadow-sm flex flex-col h-full xl:col-span-2">
      <h2 className="text-sm font-semibold text-slate-900 dark:text-white mb-4">Recent Reports</h2>
      
      <div className="flex-1 overflow-auto">
        <table className="w-full text-left text-xs">
          <thead className="text-slate-500 dark:text-slate-400 border-b border-slate-100 dark:border-slate-800">
            <tr>
              <th className="font-medium pb-2 pr-2">Report Name</th>
              <th className="font-medium pb-2 px-2">Category</th>
              <th className="font-medium pb-2 px-2">Type</th>
              <th className="font-medium pb-2 px-2">Generated By</th>
              <th className="font-medium pb-2 px-2">Generated At</th>
              <th className="font-medium pb-2 px-2 text-center">Format</th>
              <th className="font-medium pb-2 pl-2 text-center">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
            {reports.map((report) => {
              const Icon = report.icon;
              return (
                <tr key={report.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                  <td className="py-3 pr-2 flex items-center gap-2">
                    <div className="p-1.5 rounded-md bg-brand-blue/10 text-brand-blue dark:bg-brand-blue/20">
                      <Icon className="w-3.5 h-3.5" />
                    </div>
                    <span className="text-slate-900 dark:text-slate-200 font-medium truncate max-w-[150px]" title={report.name}>
                      {report.name}
                    </span>
                  </td>
                  <td className="py-3 px-2 text-slate-600 dark:text-slate-300 truncate max-w-[120px]">{report.category}</td>
                  <td className="py-3 px-2 text-slate-600 dark:text-slate-400">{report.type}</td>
                  <td className="py-3 px-2 text-slate-600 dark:text-slate-300">{report.by}</td>
                  <td className="py-3 px-2 text-slate-500 dark:text-slate-400 whitespace-nowrap">{report.time}</td>
                  <td className="py-3 px-2 text-center">
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-red-50 text-red-600 border border-red-200 dark:bg-red-900/30 dark:text-red-400 dark:border-red-800/50">
                      PDF
                    </span>
                  </td>
                  <td className="py-3 pl-2">
                    <div className="flex items-center justify-center gap-1">
                      <button className="p-1 text-slate-400 hover:text-brand-blue hover:bg-slate-100 dark:hover:bg-slate-800 rounded-md transition-colors" title="Download">
                        <Download className="w-4 h-4" />
                      </button>
                      <button className="p-1 text-slate-400 hover:text-slate-600 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-md transition-colors">
                        <MoreVertical className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      
      <div className="flex justify-end mt-4 pt-2 border-t border-slate-100 dark:border-slate-800">
        <button className="text-xs text-brand-blue font-medium hover:underline flex items-center gap-1">
          View all reports <ArrowRight className="w-3 h-3" />
        </button>
      </div>
    </div>
  );
}
